package SSP;

import java.awt.AWTException;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class Signupwithsplitandnoairgapped {
	WebDriver driver;
	WebDriver driver1;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("Signupwithsplitandnoairgapped.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	public void start() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:7000");
		driver.manage().window().maximize();
		Thread.sleep(1000);
	}
	@Test
	public void test00() throws InterruptedException, AWTException {
		start();
		driver.findElement(By.xpath("//a[@href='/register']")).click();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserCompany']")).sendKeys("test");
		driver.findElement(By.xpath("//input[@id='signupCompanyCity']")).sendKeys("hyd");
		driver.findElement(By.xpath("//textarea[@id='signupCompanyAddress']")).sendKeys("hyd");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath1@test7.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		WebElement e=driver.findElement(By.xpath("//span[@id='captchaText']"));
		String a3=e.getText();
		WebElement e1=driver.findElement(By.xpath("//input[@id='signupCaptchaInput']"));
		e1.sendKeys(a3);
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("(//span[@class='form-sub-heading display-table-cell user-form'])[2]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='form-control register-code-input']")).sendKeys("1");
		driver.findElement(By.xpath("(//input[@class='form-control register-code-input'])[2]")).sendKeys("2");
		driver.findElement(By.xpath("(//input[@class='form-control register-code-input'])[3]")).sendKeys("3");
		driver.findElement(By.xpath("(//input[@class='form-control register-code-input'])[4]")).sendKeys("4");
		driver.findElement(By.xpath("(//input[@class='form-control register-code-input'])[5]")).sendKeys("5");
		driver.findElement(By.xpath("(//input[@class='form-control register-code-input'])[6]")).sendKeys("6");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(500);
		String a4=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[2]/div/div/section[2]/div/div/div/div/div[1]/div/div[1]/span")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//span[@class='custom-radio'])[2]")).click();
		String a6=driver.findElement(By.xpath("(//input[@class='trial-platform-input'])[2]")).getAttribute("value");
		String a7=driver.findElement(By.xpath("//div[@class='platform-box active']")).getAttribute("class");
		Thread.sleep(1000);
		String a12=driver.findElement(By.xpath("//input[@id='isSplitLicenseInput']")).getAttribute("id");
		driver.findElement(By.xpath("(//span[@class='custom-checkbox'])[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='generateTrialLicenseBtn']")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		String a9=driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[2]/div[1]/div/section/div/div/div/div[1]/div/div/span")).getText();
		Thread.sleep(1000);
		String a10=driver.findElement(By.xpath("//span[@class='copy-code']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='copy-code']")).click();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver1=new ChromeDriver();
		driver1.get("http://192.168.2.19:9090");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		//driver1.findElement(By.xpath("//button[@id='modelSubmitBtn']")).click();
		//Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='companyInput']")).sendKeys("test");
		driver1.findElement(By.xpath("//input[@id='nameInput']")).sendKeys("sharath");
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("sharath");
		driver1.findElement(By.xpath("//input[@id='signupPassword']")).sendKeys("123456");
		driver1.findElement(By.xpath("//input[@id='licenceInput']")).sendKeys(Keys.chord(Keys.CONTROL, "v"));
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//*[@id=\"submitBtn\"]")).click();
		driver1.findElement(By.xpath("//input[@id='licenseUsersInput']"));
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//*[@id=\"submitBtn\"]")).click();
		Thread.sleep(500);
		String a13=driver1.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Don't enter no. of users count");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter valid password");
		test.info("Enter valid mobile num");
		test.info("Enter valid captcha");
		test.info("Click on next button");
		test.info("Enter valid password");
		test.info("Click on submit");
		test.info("Select the platform");
		test.info("Select the checkbox of split license");
		test.info("Don't select the checkbox of air gapped");
		test.info("Click on start trail");
		test.info("In license page, Copy the code");
		test.info("Open another grit url: http://192.168.2.19:9090");
		test.info("Click on submit");
		test.info("Enter company name");
		test.info("Enter user name");
		test.info("Enter user id");
		test.info("Enter password");
		test.info("Paste the license code");
		test.info("Don't enter the no. of user count");
		test.info("click on submit");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "VERIFY ACCOUNT");
		test.pass(a2);
		Assert.assertEquals(a4, "Verified!");
		test.pass(a4);
		Assert.assertEquals(a5, "Trial");
		test.pass(a5);
		Assert.assertEquals(a6, "windows");
		test.pass(a6);
		Assert.assertEquals(a7, "platform-box active");
		test.pass(a7);
		Assert.assertEquals(a12, "isSplitLicenseInput");
		test.pass(a12);
		Assert.assertEquals(a8, "Trial License Created");
		test.pass(a8);
		Assert.assertEquals(a9, "License");
		test.pass(a9);
		Assert.assertEquals(a10, "copy-code");
		test.pass(a10);
		Assert.assertEquals(a11, "Copied!");
		test.pass(a11);
		Assert.assertEquals(a13, "Value for Number of Users is required");
		test.pass(a13);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
		driver1.close();
	}
	@Test
	public void test01() throws InterruptedException, AWTException {
		start();
		driver.findElement(By.xpath("//input[@id='loginUsername']")).sendKeys("sharath1@test1.com");
		driver.findElement(By.xpath("//input[@id='loginPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='loginBtn']")).click();
		Thread.sleep(2000);
		String a10=driver.findElement(By.xpath("//span[@class='copy-code']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='copy-code']")).click();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver1=new ChromeDriver();
		driver1.get("http://192.168.2.19:9090");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='companyInput']")).sendKeys("test");
		driver1.findElement(By.xpath("//input[@id='nameInput']")).sendKeys("sharath");
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("sharath");
		driver1.findElement(By.xpath("//input[@id='signupPassword']")).sendKeys("123456");
		driver1.findElement(By.xpath("//input[@id='licenceInput']")).sendKeys(Keys.chord(Keys.CONTROL, "v"));
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//*[@id=\"submitBtn\"]")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='licenseUsersInput']")).sendKeys("5");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//*[@id=\"submitBtn\"]")).click();
		Thread.sleep(1000);
		String a1=driver1.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("sharath");
		driver1.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(8000);
		driver1.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		Thread.sleep(2000);
		driver1.switchTo().frame(0);
		driver1.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[6]")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='licenseRenewalTokenInput']")).sendKeys(Keys.chord(Keys.CONTROL, "v"));
		driver1.findElement(By.xpath("//button[@id='licenseRenewalBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='licenseRenewalUserCountInput']"));
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='licenseRenewalBtn']")).click();
		Thread.sleep(1000);
		String a2=driver1.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Don't enter user count by adding license");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Enter username");
		test.info("Enter password");
		test.info("Click on login button");
		test.info("In license page, Copy the code");
		test.info("Open another grit url: http://192.168.2.19:9090");
		test.info("Click on submit");
		test.info("Enter company name");
		test.info("Enter user name");
		test.info("Enter user id");
		test.info("Enter password");
		test.info("Paste the license code");
		test.info("Enter the no. of user count");
		test.info("click on submit");
		test.info("In login page, Enter username");
		test.info("Enter password");
		test.info("Click on login");
		test.info("Click on dashboard icon");
		test.info("Click on license tab");
		test.info("Click on Enter license code");
		test.info("Paste the license code");
		test.info("Click on activate");
		test.info("Don't enter no. of users");
		test.info("Click on activate");
		test.info("EXPECTED RESULT:: It should add the license");
		Assert.assertEquals(a10, "copy-code");
		test.pass(a10);
		Assert.assertEquals(a11, "Copied!");
		test.pass(a11);
		Assert.assertEquals(a2, "Value for Number of Users is required");
		test.pass(a2);
		Assert.assertEquals(a1, "");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is adding the license");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
		driver1.close();
	}
	@Test
	public void test02() throws InterruptedException, AWTException {
		start();
		driver.findElement(By.xpath("//input[@id='loginUsername']")).sendKeys("sharath1@test1.com");
		driver.findElement(By.xpath("//input[@id='loginPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='loginBtn']")).click();
		Thread.sleep(2000);
		String a10=driver.findElement(By.xpath("//span[@class='copy-code']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='copy-code']")).click();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver1=new ChromeDriver();
		driver1.get("http://192.168.2.19:9090");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("sharath");
		driver1.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(8000);
		driver1.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		Thread.sleep(2000);
		driver1.switchTo().frame(0);
		driver1.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[6]")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='licenseRenewalTokenInput']")).sendKeys(Keys.chord(Keys.CONTROL, "v"));
		driver1.findElement(By.xpath("//button[@id='licenseRenewalBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='licenseRenewalUserCountInput']")).sendKeys("0");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='licenseRenewalBtn']")).click();
		Thread.sleep(1000);
		String a2=driver1.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Enter user count with '0' by adding license");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Enter username");
		test.info("Enter password");
		test.info("Click on login button");
		test.info("In license page, Copy the code");
		test.info("Open another grit url: http://192.168.2.19:9090");
		test.info("In login page, Enter username");
		test.info("Enter password");
		test.info("Click on login");
		test.info("Click on dashboard icon");
		test.info("Click on license tab");
		test.info("Click on Enter license code");
		test.info("Paste the license code");
		test.info("Click on activate");
		test.info("Enter no. of users with '0'");
		test.info("Click on activate");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a10, "copy-code");
		test.pass(a10);
		Assert.assertEquals(a11, "Copied!");
		test.pass(a11);
		Assert.assertEquals(a2, "Invalid value for Number of Users");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
		driver1.close();
	}
	@Test
	public void test03() throws InterruptedException, AWTException {
		start();
		driver.findElement(By.xpath("//input[@id='loginUsername']")).sendKeys("sharath6@test1.com");
		driver.findElement(By.xpath("//input[@id='loginPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='loginBtn']")).click();
		Thread.sleep(2000);
		String a10=driver.findElement(By.xpath("//span[@class='copy-code']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='copy-code']")).click();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver1=new ChromeDriver();
		driver1.get("http://192.168.2.19:9090");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("sharath");
		driver1.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(8000);
		driver1.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		Thread.sleep(2000);
		driver1.switchTo().frame(0);
		driver1.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[6]")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='licenseRenewalTokenInput']")).sendKeys(Keys.chord(Keys.CONTROL, "v"));
		driver1.findElement(By.xpath("//button[@id='licenseRenewalBtn']")).click();
		Thread.sleep(1000);
		String a2=driver1.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Enter invalid license");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Enter username");
		test.info("Enter password");
		test.info("Click on login button");
		test.info("In license page, Copy the code");
		test.info("Open another grit url: http://192.168.2.19:9090");
		test.info("In login page, Enter username");
		test.info("Enter password");
		test.info("Click on login");
		test.info("Click on dashboard icon");
		test.info("Click on license tab");
		test.info("Click on Enter license code");
		test.info("Paste the invalid license code");
		test.info("Click on activate");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a10, "copy-code");
		test.pass(a10);
		Assert.assertEquals(a11, "Copied!");
		test.pass(a11);
		Assert.assertEquals(a2, "Invalid License Code!");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
		driver1.close();
	}
	@Test
	public void test04() throws InterruptedException, AWTException {
		start();
		driver.findElement(By.xpath("//input[@id='loginUsername']")).sendKeys("sharath1@test1.com");
		driver.findElement(By.xpath("//input[@id='loginPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='loginBtn']")).click();
		Thread.sleep(2000);
		String a10=driver.findElement(By.xpath("//span[@class='copy-code']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='copy-code']")).click();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver1=new ChromeDriver();
		driver1.get("http://192.168.2.19:9090");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("sharath");
		driver1.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(8000);
		driver1.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		Thread.sleep(2000);
		driver1.switchTo().frame(0);
		driver1.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[6]")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='licenseRenewalTokenInput']")).sendKeys(Keys.chord(Keys.CONTROL, "v"));
		driver1.findElement(By.xpath("//button[@id='licenseRenewalBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='licenseRenewalUserCountInput']")).sendKeys("6");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='licenseRenewalBtn']")).click();
		Thread.sleep(1000);
		String a2=driver1.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Enter user count with '6' more than license users");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Enter username");
		test.info("Enter password");
		test.info("Click on login button");
		test.info("In license page, Copy the code");
		test.info("Open another grit url: http://192.168.2.19:9090");
		test.info("In login page, Enter username");
		test.info("Enter password");
		test.info("Click on login");
		test.info("Click on dashboard icon");
		test.info("Click on license tab");
		test.info("Click on Enter license code");
		test.info("Paste the license code");
		test.info("Click on activate");
		test.info("Enter user count : 6(more than license)");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a10, "copy-code");
		test.pass(a10);
		Assert.assertEquals(a11, "Copied!");
		test.pass(a11);
		Assert.assertEquals(a2, "User count exceeded. Error Code: 1101");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
		driver1.close();
	}
	@Test
	public void test05() throws InterruptedException, AWTException {
		start();
		driver.findElement(By.xpath("//input[@id='loginUsername']")).sendKeys("sharath1@test1.com");
		driver.findElement(By.xpath("//input[@id='loginPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='loginBtn']")).click();
		Thread.sleep(2000);
		String a10=driver.findElement(By.xpath("//span[@class='copy-code']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='copy-code']")).click();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver1=new ChromeDriver();
		driver1.get("http://192.168.2.19:9090");
		driver1.manage().window().maximize();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("sharath");
		driver1.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(8000);
		driver1.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		Thread.sleep(2000);
		driver1.switchTo().frame(0);
		driver1.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[6]")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='licenseRenewalTokenInput']")).sendKeys(Keys.chord(Keys.CONTROL, "v"));
		driver1.findElement(By.xpath("//button[@id='licenseRenewalBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='licenseRenewalUserCountInput']")).sendKeys("5");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='licenseRenewalBtn']")).click();
		Thread.sleep(2000);
		String a2=driver1.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//span[@class='license-activation-status activated']")).getText();
		ExtentTest test = extent.createTest("Enter user count with '5' by adding license");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Enter username");
		test.info("Enter password");
		test.info("Click on login button");
		test.info("In license page, Copy the code");
		test.info("Open another grit url: http://192.168.2.19:9090");
		test.info("In login page, Enter username");
		test.info("Enter password");
		test.info("Click on login");
		test.info("Click on dashboard icon");
		test.info("Click on license tab");
		test.info("Click on Enter license code");
		test.info("Paste the license code");
		test.info("Click on activate");
		test.info("Enter no. of users count : 5");
		test.info("Click on activate");
		test.info("EXPECTED RESULT:: It should add the license");
		Assert.assertEquals(a10, "copy-code");
		test.pass(a10);
		Assert.assertEquals(a11, "Copied!");
		test.pass(a11);
		Assert.assertEquals(a2, "License Activated!");
		test.pass(a2);
		Assert.assertEquals(a4, "Activated");
		test.pass(a4);
		test.log(Status.PASS,"ACTUAL RESULT::  It is adding the license");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
		driver1.close();
	}
	@Test
	public void test06() throws InterruptedException, AWTException {
		start();
		driver.findElement(By.xpath("//input[@id='loginUsername']")).sendKeys("sharath1@test1.com");
		driver.findElement(By.xpath("//input[@id='loginPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='loginBtn']")).click();
		Thread.sleep(2000);
		String a10=driver.findElement(By.xpath("//span[@class='copy-code']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='copy-code']")).click();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver1=new ChromeDriver();
		driver1.get("http://192.168.2.19:9090");
		driver1.manage().window().maximize();
		driver1.findElement(By.xpath("//input[@id='username']")).sendKeys("sharath");
		driver1.findElement(By.xpath("//input[@id='password']")).sendKeys("123456");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(8000);
		driver1.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		Thread.sleep(2000);
		driver1.switchTo().frame(0);
		driver1.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[6]")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='licenseRenewalTokenInput']")).sendKeys(Keys.chord(Keys.CONTROL, "v"));
		driver1.findElement(By.xpath("//button[@id='licenseRenewalBtn']")).click();
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//input[@id='licenseRenewalUserCountInput']")).sendKeys("5");
		Thread.sleep(1000);
		driver1.findElement(By.xpath("//button[@id='licenseRenewalBtn']")).click();
		Thread.sleep(2000);
		String a2=driver1.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Enter user count with '5' after license is completed");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Enter username");
		test.info("Enter password");
		test.info("Click on login button");
		test.info("In license page, Copy the code");
		test.info("Open another grit url: http://192.168.2.19:9090");
		test.info("In login page, Enter username");
		test.info("Enter password");
		test.info("Click on login");
		test.info("Click on dashboard icon");
		test.info("Click on license tab");
		test.info("Click on Enter license code");
		test.info("Paste the invalid license code");
		test.info("Click on activate");
		test.info("Enter no. of users count : 5");
		test.info("Click on activate");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a10, "copy-code");
		test.pass(a10);
		Assert.assertEquals(a11, "Copied!");
		test.pass(a11);
		Assert.assertEquals(a2, "License is already activated");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
		driver1.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
