package SSP;

import java.awt.AWTException;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class SSPNewUser {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("SSPNewUser.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	public void start() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:7000");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//a[@href='/register']")).click();
		Thread.sleep(2000);
	}
	@Test
	public void test00() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		ExtentTest test = extent.createTest("Click on new user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("EXPECTED RESULT:: It should display register page");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying register page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on next button without entering data");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Click on next button without entering data");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "Please enter company name");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserCompany']")).sendKeys("test");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on next button by entering company name");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display User details page");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying user details page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserCompany']")).sendKeys("test");
		driver.findElement(By.xpath("//input[@id='signupCompanyCity']")).sendKeys("hyd");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on next button by enter company name & city");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display User details page");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying user details page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	public void start1() throws InterruptedException {
		driver.findElement(By.xpath("//input[@id='signupUserCompany']")).sendKeys("test");
		driver.findElement(By.xpath("//input[@id='signupCompanyCity']")).sendKeys("hyd");
		driver.findElement(By.xpath("//textarea[@id='signupCompanyAddress']")).sendKeys("hyd");
	}
	@Test
	public void test04() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on next button by enter company name,city & address");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display User details page");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying user details page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserCompany']")).sendKeys("");
		driver.findElement(By.xpath("//input[@id='signupCompanyCity']")).sendKeys("hyd");
		driver.findElement(By.xpath("//textarea[@id='signupCompanyAddress']")).sendKeys("hyd");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on next button by enter city & address");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Don't enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display User details page");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "Please enter company name");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying user details page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		String a1=driver.findElement(By.xpath("//a[@href='/login']")).getText();
		driver.findElement(By.xpath("//a[@href='/login']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on login button after entering company name,city & address");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on login button");
		test.info("EXPECTED RESULT:: It should display login details page");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "Login");
		test.pass(a1);
		Assert.assertEquals(a2, "Login");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying login details page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Without entering any data");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Click on next button without entering data");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Please enter your name");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter your name");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Please enter your email");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test09() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter email as only name");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter invalid email");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Please enter a valid email");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test10() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath@test.com");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter valid email & name");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Please enter your password");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test11() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath@gmail.com");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter valid email with @gmail & name");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email with @gmail");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Email address is not allowed");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test12() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath@yahoo.com");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter valid email with @yahoo & name");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email with @yahoo");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Email address is not allowed");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test13() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath@test8.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter valid name,email & password");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter password");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Captcha code is required");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test14() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath@test8.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter valid name,email & invalid password");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter invalid password");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Password must be at least 6 characters long");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test15() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath@test8.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter valid name,email & invalid password");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter invalid password");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Password must be at least 6 characters long");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test16() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath@test8.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//input[@id='registerMobileNumber']")).sendKeys("987654");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter valid name,email,password & invalid mobile num");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter valid password");
		test.info("Enter invalid mobile num");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Invalid Mobile Number");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test17() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath@test8.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//input[@id='registerMobileNumber']")).sendKeys("9876541236");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter valid name,email,password & mobile num");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter valid password");
		test.info("Enter valid mobile num");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Captcha code is required");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test18() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath@test8.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//input[@id='registerMobileNumber']")).sendKeys("9876541236");
		String a3=driver.findElement(By.xpath("//a[@href='/login']")).getText();
		driver.findElement(By.xpath("//a[@href='/login']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter data & Click on login");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter valid password");
		test.info("Enter valid mobile num");
		test.info("Click on login button");
		test.info("EXPECTED RESULT:: It should display login page");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a3, "Login");
		test.pass(a3);
		Assert.assertEquals(a2, "Login");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying login page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test19() throws InterruptedException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath@test8.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//input[@id='registerMobileNumber']")).sendKeys("9876541236");
		driver.findElement(By.xpath("//input[@id='signupCaptchaInput']")).sendKeys("FTERDFAS");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter data & Enter invalid captcha");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter valid password");
		test.info("Enter valid mobile num");
		test.info("Enter invalid captcha");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Incorrect Captcha Code");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test20() throws InterruptedException, AWTException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath@test8.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//input[@id='registerMobileNumber']")).sendKeys("9876541236");
		WebElement e=driver.findElement(By.xpath("//span[@id='captchaText']"));
		String a3=e.getText();
		WebElement e1=driver.findElement(By.xpath("//input[@id='signupCaptchaInput']"));
		e1.sendKeys(a3);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='display-table-cell register-hint-wrapper font-14']")).click();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter data & Enter existing email & Enter captcha");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter existing email");
		test.info("Enter valid password");
		test.info("Enter valid mobile num");
		test.info("Enter valid captcha");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Email is already registered.");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test21() throws InterruptedException, AWTException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath6@test4.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//input[@id='registerMobileNumber']")).sendKeys("9876541236");
		WebElement e=driver.findElement(By.xpath("//span[@id='captchaText']"));
		String a3=e.getText();
		WebElement e1=driver.findElement(By.xpath("//input[@id='signupCaptchaInput']"));
		e1.sendKeys(a3);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='display-table-cell register-hint-wrapper font-14']")).click();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter data & Enter existing mobile num & Enter captcha");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter invalid email");
		test.info("Enter valid password");
		test.info("Enter existing mobile num");
		test.info("Enter valid captcha");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "Mobile number is already registered.");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test22() throws InterruptedException, AWTException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath6@test4.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//input[@id='registerMobileNumber']")).sendKeys("9876123451");
		WebElement e=driver.findElement(By.xpath("//span[@id='captchaText']"));
		String a3=e.getText();
		WebElement e1=driver.findElement(By.xpath("//input[@id='signupCaptchaInput']"));
		e1.sendKeys(a3);
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("(//span[@class='form-sub-heading display-table-cell user-form'])[2]")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In user details,Enter data & Enter captcha");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter valid password");
		test.info("Enter valid mobile num");
		test.info("Enter valid captcha");
		test.info("Click on next button");
		test.info("EXPECTED RESULT:: It should display verify account page");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "VERIFY ACCOUNT");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying verify account page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test23() throws InterruptedException, AWTException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath6@test4.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//input[@id='registerMobileNumber']")).sendKeys("9876123451");
		WebElement e=driver.findElement(By.xpath("//span[@id='captchaText']"));
		String a3=e.getText();
		WebElement e1=driver.findElement(By.xpath("//input[@id='signupCaptchaInput']"));
		e1.sendKeys(a3);
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("(//span[@class='form-sub-heading display-table-cell user-form'])[2]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In Verify account,Click on submit with entering password");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter valid password");
		test.info("Enter valid mobile num");
		test.info("Enter valid captcha");
		test.info("Click on next button");
		test.info("Don't enter password");
		test.info("In verify account, Click on submit");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "VERIFY ACCOUNT");
		test.pass(a2);
		Assert.assertEquals(a4, "Please enter Verification Code");
		test.pass(a4);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test24() throws InterruptedException, AWTException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath6@test4.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//input[@id='registerMobileNumber']")).sendKeys("9876123451");
		WebElement e=driver.findElement(By.xpath("//span[@id='captchaText']"));
		String a3=e.getText();
		WebElement e1=driver.findElement(By.xpath("//input[@id='signupCaptchaInput']"));
		e1.sendKeys(a3);
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("(//span[@class='form-sub-heading display-table-cell user-form'])[2]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='form-control register-code-input']")).sendKeys("1");
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In verify account, Enter invalid password");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter valid password");
		test.info("Enter valid mobile num");
		test.info("Enter valid captcha");
		test.info("Click on next button");
		test.info("Enter invalid password");
		test.info("Click on submit");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "VERIFY ACCOUNT");
		test.pass(a2);
		Assert.assertEquals(a4, "Invalid Verification Code");
		test.pass(a4);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test25() throws InterruptedException, AWTException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath6@test4.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//input[@id='registerMobileNumber']")).sendKeys("9876123451");
		WebElement e=driver.findElement(By.xpath("//span[@id='captchaText']"));
		String a3=e.getText();
		WebElement e1=driver.findElement(By.xpath("//input[@id='signupCaptchaInput']"));
		e1.sendKeys(a3);
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("(//span[@class='form-sub-heading display-table-cell user-form'])[2]")).getText();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//a[@href='/login']")).getText();
		driver.findElement(By.xpath("//a[@href='/login']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In verify account, Click on login");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter valid password");
		test.info("Enter valid mobile num");
		test.info("Enter valid captcha");
		test.info("Click on next button");
		test.info("Enter login button in verify account");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "VERIFY ACCOUNT");
		test.pass(a2);
		Assert.assertEquals(a4, "Login");
		test.pass(a4);
		Assert.assertEquals(a5, "Login");
		test.pass(a5);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	public void password() {
		driver.findElement(By.xpath("//input[@class='form-control register-code-input']")).sendKeys("1");
		driver.findElement(By.xpath("(//input[@class='form-control register-code-input'])[2]")).sendKeys("2");
		driver.findElement(By.xpath("(//input[@class='form-control register-code-input'])[3]")).sendKeys("3");
		driver.findElement(By.xpath("(//input[@class='form-control register-code-input'])[4]")).sendKeys("4");
		driver.findElement(By.xpath("(//input[@class='form-control register-code-input'])[5]")).sendKeys("5");
		driver.findElement(By.xpath("(//input[@class='form-control register-code-input'])[6]")).sendKeys("6");
	}
	@Test
	public void test26() throws InterruptedException, AWTException {
		start();
		String a=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		start1();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='form-sub-heading display-table-cell user-form']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='signupUserName']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@id='signupUserEmail']")).sendKeys("sharath6@test4.com");
		driver.findElement(By.xpath("//input[@id='signupUserPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//input[@id='registerMobileNumber']")).sendKeys("9876512465");
		WebElement e=driver.findElement(By.xpath("//span[@id='captchaText']"));
		String a3=e.getText();
		WebElement e1=driver.findElement(By.xpath("//input[@id='signupCaptchaInput']"));
		e1.sendKeys(a3);
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("(//span[@class='form-sub-heading display-table-cell user-form'])[2]")).getText();
		Thread.sleep(1000);
		password();
		driver.findElement(By.xpath("//button[@id='registerBtn']")).click();
		Thread.sleep(500);
		String a4=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[2]/div/div/section[2]/div/div/div/div/div[1]/div/div[1]/span")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In verify account, Enter valid password");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Click on new user");
		test.info("Enter company name");
		test.info("Enter city name");
		test.info("Enter address");
		test.info("Click on next button");
		test.info("Enter your name");
		test.info("Enter valid email");
		test.info("Enter valid password");
		test.info("Enter valid mobile num");
		test.info("Enter valid captcha");
		test.info("Click on next button");
		test.info("Enter valid password");
		test.info("Click on submit");
		test.info("EXPECTED RESULT:: It should create the account");
		Assert.assertEquals(a, "Register");
		test.pass(a);
		Assert.assertEquals(a1, "USER DETAILS");
		test.pass(a1);
		Assert.assertEquals(a2, "VERIFY ACCOUNT");
		test.pass(a2);
		Assert.assertEquals(a4, "Verified!");
		test.pass(a4);
		Assert.assertEquals(a5, "Trial");
		test.pass(a5);
		test.log(Status.PASS,"ACTUAL RESULT::  It is creating the account");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test27() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:7000");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@id='loginUsername']")).sendKeys("sharath6@test3.com");
		driver.findElement(By.xpath("//input[@id='loginPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='loginBtn']")).click();
		Thread.sleep(2000);
		String a5=driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[2]/div/div/section[2]/div/div/div/div/div[1]/div/div[1]/span")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='profile-dropdown-wrapper']")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("//div[@class='profile-options-wrapper']")).getText();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("//div[@data-item='profile']")).getText();
		driver.findElement(By.xpath("//div[@data-item='profile']")).click();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In trail page, Click on profile");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Enter username");
		test.info("Enter password");
		test.info("Click on login button");
		test.info("Click on profile");
		test.info("Click on profile info");
		test.info("EXPECTED RESULT:: It should display profile of the user");
		Assert.assertEquals(a5, "Trial");
		test.pass(a5);
		Assert.assertEquals(a6, "Profile Info\n"
				+ "Logout");
		test.pass(a6);
		Assert.assertEquals(a7, "Profile Info");
		test.pass(a7);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying profile of the user");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test28() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:7000");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@id='loginUsername']")).sendKeys("sharath6@test3.com");
		driver.findElement(By.xpath("//input[@id='loginPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='loginBtn']")).click();
		Thread.sleep(2000);
		String a5=driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[2]/div/div/section[2]/div/div/div/div/div[1]/div/div[1]/span")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='profile-dropdown-wrapper']")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("//div[@class='profile-options-wrapper']")).getText();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("//div[@data-item='logout']")).getText();
		driver.findElement(By.xpath("//div[@data-item='logout']")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@data-font='regular']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In trail page, Click on logout");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Enter username");
		test.info("Enter password");
		test.info("Click on login button");
		test.info("Click on profile");
		test.info("Click on Logout");
		test.info("EXPECTED RESULT:: It should logout the user");
		Assert.assertEquals(a5, "Trial");
		test.pass(a5);
		Assert.assertEquals(a6, "Profile Info\n"
				+ "Logout");
		test.pass(a6);
		Assert.assertEquals(a7, "Logout");
		test.pass(a7);
		Assert.assertEquals(a4, "Login");
		test.pass(a4);
		test.log(Status.PASS,"ACTUAL RESULT::  It is logging out of the user");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test29() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:7000");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@id='loginUsername']")).sendKeys("sharath6@test3.com");
		driver.findElement(By.xpath("//input[@id='loginPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='loginBtn']")).click();
		Thread.sleep(2000);
		String a5=driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[2]/div/div/section[2]/div/div/div/div/div[1]/div/div[1]/span")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='generateTrialLicenseBtn']")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In trail page, Click on start trail without selecting platform");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Enter username");
		test.info("Enter password");
		test.info("Click on login button");
		test.info("Click on profile");
		test.info("Click on start trail without selecting platform");
		test.info("EXPECTED RESULT:: It should display error msg");
		Assert.assertEquals(a5, "Trial");
		test.pass(a5);
		Assert.assertEquals(a4, "Please select a platform!");
		test.pass(a4);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test30() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.19:7000");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@id='loginUsername']")).sendKeys("sharath6@test3.com");
		driver.findElement(By.xpath("//input[@id='loginPassword']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='loginBtn']")).click();
		Thread.sleep(2000);
		String a5=driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[2]/div/div/section[2]/div/div/div/div/div[1]/div/div[1]/span")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//span[@class='custom-radio'])[2]")).click();
		String a4=driver.findElement(By.xpath("(//input[@class='trial-platform-input'])[2]")).getAttribute("value");
		String a2=driver.findElement(By.xpath("//div[@class='platform-box active']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//button[@id='generateTrialLicenseBtn']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[2]/div[1]/div/section/div/div/div/div[1]/div/div/span")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("In trail page, Select the platform & start trail");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Enter username");
		test.info("Enter password");
		test.info("Click on login button");
		test.info("Select the platform");
		test.info("Click on start trail");
		test.info("EXPECTED RESULT:: It should display dashboard page");
		Assert.assertEquals(a5, "Trial");
		test.pass(a5);
		Assert.assertEquals(a4, "windows");
		test.pass(a4);
		Assert.assertEquals(a2, "platform-box active");
		test.pass(a2);
		Assert.assertEquals(a, "Trial License Created");
		test.pass(a);
		Assert.assertEquals(a1, "License");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying dashboard page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
