package Groups_tab;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class groups {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("group.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("android");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//*[@id=\"groupsFilterSearchInput\"]")).sendKeys("123");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on groups search");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on Search");
		test.info("Enter any alphabet");
		test.info("EXPECTED RESULT ::  System should display group name in the list");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying group name in list");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test1() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("android");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsSortFilter']/option[1]")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Click on group & select sort by alphabetic");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on Dropdown");
		test.info("Click on sort by alphabetic");
		test.info("EXPECTED RESULT ::  System should sort in alphabetic order in the list");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is sorting in alphabetic order in list");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test2() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("android");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsSortFilter']/option[2]")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Click on Sort date of creation in groups");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on Dropdown");
		test.info("Click on sort by date of creation");
		test.info("EXPECTED RESULT ::  System should sort date of creation in the list");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is sorting date of creation in list");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test3() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsSortFilter']/option[3]")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Click on sort most members in groups");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on Dropdown");
		test.info("Click on sort by most members");
		test.info("EXPECTED RESULT ::  System should sort most members in the list");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is sorting most members in list");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test4() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[2]")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Click on actions dropdown & select delete group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on Action Dropdown");
		test.info("Select delete group");
		test.info("EXPECTED RESULT ::  System should display please select atleast one group");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select atleast one group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test5() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[3]")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Click on actions dropdown & select delete all msgs & files");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on Action Dropdown");
		test.info("Select delete all msgs & files");
		test.info("EXPECTED RESULT ::  System should display please select atleast one group");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select at least one group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test6() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[4]")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Click on actions dropdown & select delete all msgs");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on Action Dropdown");
		test.info("Select delete all msgs");
		test.info("EXPECTED RESULT ::  System should display please select atleast one group");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select at least one group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test7() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[5]")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Click on actions dropdown & select delete all files");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on Action Dropdown");
		test.info("Select delete all files");
		test.info("EXPECTED RESULT ::  System should display please select atleast one group");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select at least one group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test8() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='groupsFilterSearchInput']")).sendKeys("123");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsSortFilter']/option[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[5]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='reset-btn']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Click on reset button");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Search any group name");
		test.info("Click on dropdown & select sort by date of creation");
		test.info("Click on Action Dropdown");
		test.info("Select delete all files");
		test.info("EXPECTED RESULT ::  System should display please select atleast one group");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Please select at least one group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test9() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[5]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Select any group & click on actions delete all files");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on checkbox of group");
		test.info("Click on Action Dropdown");
		test.info("Select delete all files");
		test.info("Select Yes in the popup notification");
		test.info("EXPECTED RESULT ::  System should delete the data of all files");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Data deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcases22() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[2]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[5]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Select multiple group & click on actions delete all files");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on checkbox of groups");
		test.info("Click on Action Dropdown");
		test.info("Select delete all files");
		test.info("Select Yes in the popup notification");
		test.info("EXPECTED RESULT ::  System should delete the data of all files");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Data deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcase10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Select any group & click on actions delete all msgs");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on checkbox of group");
		test.info("Click on Action Dropdown");
		test.info("Select delete all msgs");
		test.info("Select Yes in the popup notification");
		test.info("EXPECTED RESULT ::  System should display delete the data of all msgs");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Data deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcases21() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[2]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Select multiple group & click on actions delete all msgs");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on checkbox of groups");
		test.info("Click on Action Dropdown");
		test.info("Select delete all msgs");
		test.info("Select Yes in the popup notification");
		test.info("EXPECTED RESULT ::  System should display delete the data of all msgs");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Data deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcase11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Select any group & click on actions delete all msgs & files");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on checkbox of group");
		test.info("Click on Action Dropdown");
		test.info("Select delete all msgs & files");
		test.info("Select Yes in the popup notification");
		test.info("EXPECTED RESULT ::  System should display delete the data of all msgs & files");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Data deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcases20() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='page-right']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[2]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Select multiple group & click on actions delete all msgs & files");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on checkbox of groups");
		test.info("Click on Action Dropdown");
		test.info("Select delete all msgs & files");
		test.info("Select Yes in the popup notification");
		test.info("EXPECTED RESULT ::  System should display delete the data of all msgs & files");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Data deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcase12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Select any group & click on actions delete group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on checkbox of groups");
		test.info("Click on Action Dropdown");
		test.info("Select delete group");
		test.info("Select Yes in the popup notification");
		test.info("EXPECTED RESULT ::  System should display delete groups");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Group deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcase19() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[14]/div[1]/div/label")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='groupsFilterAction']/option[2]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Select multiple group & click on actions delete group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on checkbox of group");
		test.info("Click on Action Dropdown");
		test.info("Select delete group");
		test.info("Select Yes in the popup notification");
		test.info("EXPECTED RESULT ::  System should display delete group");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Group deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcase13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[8]/div/div[2]/div[1]/span\n")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Click on three dots & Click on view");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Select the group");
		test.info("Click on menu-bar");
		test.info("Click on view");
		test.info("EXPECTED RESULT ::  System should display the profile");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the profile view");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcases23() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[8]/div/div[2]/div[1]/span\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[4]/div[2]/div[1]/div/div[3]/div[1]/div[2]")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("In view click on admins");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Select the group");
		test.info("Click on menu-bar");
		test.info("Click on view");
		test.info("Click on admins");
		test.info("EXPECTED RESULT ::  System should display the view & it click on admin" );
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the profile view & clicking on admins");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcases24() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[8]/div/div[2]/div[1]/span\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[4]/div[2]/div[1]/div/div[3]/div[1]/div[3]")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("In view click on users");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Select the group");
		test.info("Click on menu-bar");
		test.info("Click on view");
		test.info("Click on users");
		test.info("EXPECTED RESULT ::  System should display the view & it click on users" );
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying the profile view & clicking on users");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcase14() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[8]/div/div[2]/div[3]/span")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Select any group & click on menubar & delete the all msgs & files");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Select any group");
		test.info("Click on menu bar");
		test.info("Select delete all msgs & files");
		test.info("Select Yes in the popup notification");
		test.info("EXPECTED RESULT ::  System should delete the data of all msgs & files");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Data deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcase15() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[8]/div/div[2]/div[4]/span")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Select any group & click on menubar & delete the all msgs");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Select any group");
		test.info("Click on menu bar");
		test.info("Select delete all msgs");
		test.info("Select Yes in the popup notification");
		test.info("EXPECTED RESULT ::  System should delete the data of all msgs");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Data deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcase16() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[8]/div/div[2]/div[5]/span\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Select any group & click on menubar & delete the all files");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Select any group");
		test.info("Click on menu bar");
		test.info("Select delete all files");
		test.info("Select Yes in the popup notification");
		test.info("EXPECTED RESULT ::  System should delete the data of all files");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Data deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcase17() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/div[8]/div/div[2]/div[2]/span")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@class='btn btn-success btn-yes']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Select any group & click on menubar & delete the group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Select any group");
		test.info("Click on menu bar");
		test.info("Select delete the group");
		test.info("Select Yes in the popup notification");
		test.info("EXPECTED RESULT ::  System should delete the data the group");
		test.log(Status.PASS ,"ACTUAL RESULT ::  Group deleted successfully");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@Test
	public void testcase18() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='page-right']")).click();
		Thread.sleep(3000);
		ExtentTest test=extent.createTest("Click on next page");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on Groups");
		test.info("Click on next page");
		test.info("EXPECTED RESULT ::  System should click on next page");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is clicking on next page");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();	
	}
	@AfterSuite
	public void endTest() {
		extent.flush();		
	}
}
