package grit_controls;

import java.awt.AWTException;
import java.io.IOException;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class Filedeck {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("FileDeck.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioDisable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioDisable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-app='filemanager']")).getAttribute("data-app");
		String a1=driver.findElement(By.xpath("//div[@style='display: none;']")).getAttribute("style");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting disable radiobutton in filedeck");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Disable button");
		Assert.assertEquals(a5, "Disable");
		test.pass(a5);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("View the filedeck icon");
		Assert.assertEquals(a, "filemanager");
		test.pass(a);
		Assert.assertEquals(a1, "display: none;");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should not display filedeck icon");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying filedeck icon");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-app='filemanager']")).getAttribute("data-app");
		driver.findElement(By.xpath("//div[@data-app='filemanager']")).click();
		String a1=driver.findElement(By.xpath("//div[@style='display: block;']")).getAttribute("style");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting enable radiobutton in filedeck");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on filedeck icon");
		Assert.assertEquals(a, "filemanager");
		test.pass(a);
		Assert.assertEquals(a1, "display: block;");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should display filedeck icon");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying filedeck icon");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-app='filemanager']")).getAttribute("data-app");
		driver.findElement(By.xpath("//div[@data-app='filemanager']")).click();
		String a1=driver.findElement(By.xpath("//div[@style='display: block;']")).getAttribute("style");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting enable radiobutton in sync");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on filedeck icon");
		Assert.assertEquals(a, "filemanager");
		test.pass(a);
		Assert.assertEquals(a1, "display: block;");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should sync the files in filedeck");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is syncing the files in filedeck");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioDisable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioDisable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-app='filemanager']")).getAttribute("data-app");
		driver.findElement(By.xpath("//div[@data-app='filemanager']")).click();
		String a1=driver.findElement(By.xpath("//div[@style='display: block;']")).getAttribute("style");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting disable radiobutton in sync");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Disable button");
		Assert.assertEquals(a6, "Disable");
		test.pass(a6);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on filedeck icon");
		Assert.assertEquals(a, "filemanager");
		test.pass(a);
		Assert.assertEquals(a1, "display: block;");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should not sync the files in filedeck");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not syncing the files in filedeck");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[5]/span[2]")).getText();
		String a8=driver.findElement(By.xpath("//span[@class='control-type-heading']")).getText();
		String a9=driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).sendKeys("10");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='fileDeckBandwidthDownloadUnit']")).click();
		String a10=driver.findElement(By.xpath("//select[@id='fileDeckBandwidthDownloadUnit']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='b']")).click();
		String a11=driver.findElement(By.xpath("//option[@value='b']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-app='filemanager']")).getAttribute("data-app");
		driver.findElement(By.xpath("//div[@data-app='filemanager']")).click();
		String a1=driver.findElement(By.xpath("//div[@style='display: block;']")).getAttribute("style");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("In downloads, Enter the data & Select the Bytes/s");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("Click on Bandwidth controls");
		Assert.assertEquals(a7, "Bandwidth controls");
		test.pass(a7);
		test.info("In download, Enter the value");
		Assert.assertEquals(a8, "Download");
		test.pass(a8);
		test.info("Click on drop down of downloads");
		Assert.assertEquals(a9, "fileDeckBandwidthDownloadSpeedInput");
		test.pass(a9);
		test.info("Select the Bytes/s in the drop down of downloads");
		Assert.assertEquals(a10, "                                                        Bytes/s\n"
				+ "                                                        kBytes/s\n"
				+ "                                                        MBytes/s\n"
				+ "                                                        GBytes/s\n"
				+ "                                                    ");
		test.pass(a10);
		Assert.assertEquals(a11, "Bytes/s");
		test.pass(a11);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on filedeck icon");
		Assert.assertEquals(a, "filemanager");
		test.pass(a);
		Assert.assertEquals(a1, "display: block;");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should select Bytes/s & It should enter the data in downloads");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting Bytes/s & It is enter the data in downloads");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[5]/span[2]")).getText();
		String a8=driver.findElement(By.xpath("//span[@class='control-type-heading']")).getText();
		String a9=driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).clear();
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).sendKeys("10");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='fileDeckBandwidthDownloadUnit']")).click();
		String a10=driver.findElement(By.xpath("//select[@id='fileDeckBandwidthDownloadUnit']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='k']")).click();
		String a11=driver.findElement(By.xpath("//option[@value='k']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-app='filemanager']")).getAttribute("data-app");
		driver.findElement(By.xpath("//div[@data-app='filemanager']")).click();
		String a1=driver.findElement(By.xpath("//div[@style='display: block;']")).getAttribute("style");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("In downloads, Enter the data & Select the kBytes/s");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("Click on Bandwidth controls");
		Assert.assertEquals(a7, "Bandwidth controls");
		test.pass(a7);
		test.info("In download, Enter the value");
		Assert.assertEquals(a8, "Download");
		test.pass(a8);
		test.info("Click on drop down of downloads");
		Assert.assertEquals(a9, "fileDeckBandwidthDownloadSpeedInput");
		test.pass(a9);
		test.info("Select the kBytes/s in the drop down of downloads");
		Assert.assertEquals(a10, "                                                        Bytes/s\n"
				+ "                                                        kBytes/s\n"
				+ "                                                        MBytes/s\n"
				+ "                                                        GBytes/s\n"
				+ "                                                    ");
		test.pass(a10);
		Assert.assertEquals(a11, "kBytes/s");
		test.pass(a11);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on filedeck icon");
		Assert.assertEquals(a, "filemanager");
		test.pass(a);
		Assert.assertEquals(a1, "display: block;");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should select kBytes/s & It should enter the data in downloads");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting kBytes/s & It is entering the data in downloads");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[5]/span[2]")).getText();
		String a8=driver.findElement(By.xpath("//span[@class='control-type-heading']")).getText();
		String a9=driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).clear();
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).sendKeys("10");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='fileDeckBandwidthDownloadUnit']")).click();
		String a10=driver.findElement(By.xpath("//select[@id='fileDeckBandwidthDownloadUnit']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='M']")).click();
		String a11=driver.findElement(By.xpath("//option[@value='M']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-app='filemanager']")).getAttribute("data-app");
		driver.findElement(By.xpath("//div[@data-app='filemanager']")).click();
		String a1=driver.findElement(By.xpath("//div[@style='display: block;']")).getAttribute("style");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("In downloads, Enter the data & Select the MBytes/s");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("Click on Bandwidth controls");
		Assert.assertEquals(a7, "Bandwidth controls");
		test.pass(a7);
		test.info("In download, Enter the value");
		Assert.assertEquals(a8, "Download");
		test.pass(a8);
		test.info("Click on drop down of downloads");
		Assert.assertEquals(a9, "fileDeckBandwidthDownloadSpeedInput");
		test.pass(a9);
		test.info("Select the MBytes/s in the drop down of downloads");
		Assert.assertEquals(a10, "                                                        Bytes/s\n"
				+ "                                                        kBytes/s\n"
				+ "                                                        MBytes/s\n"
				+ "                                                        GBytes/s\n"
				+ "                                                    ");
		test.pass(a10);
		Assert.assertEquals(a11, "MBytes/s");
		test.pass(a11);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on filedeck icon");
		Assert.assertEquals(a, "filemanager");
		test.pass(a);
		Assert.assertEquals(a1, "display: block;");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should select MBytes/s & It should enter the data in downloads");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting MBytes/s & It is entering the data in downloads");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[5]/span[2]")).getText();
		String a8=driver.findElement(By.xpath("//span[@class='control-type-heading']")).getText();
		String a9=driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).clear();
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).sendKeys("10");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='fileDeckBandwidthDownloadUnit']")).click();
		String a10=driver.findElement(By.xpath("//select[@id='fileDeckBandwidthDownloadUnit']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='G']")).click();
		String a11=driver.findElement(By.xpath("//option[@value='G']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-app='filemanager']")).getAttribute("data-app");
		driver.findElement(By.xpath("//div[@data-app='filemanager']")).click();
		String a1=driver.findElement(By.xpath("//div[@style='display: block;']")).getAttribute("style");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("In downloads, Enter the data & Select the GBytes/s");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("Click on Bandwidth controls");
		Assert.assertEquals(a7, "Bandwidth controls");
		test.pass(a7);
		test.info("In download, Enter the value");
		Assert.assertEquals(a8, "Download");
		test.pass(a8);
		test.info("Click on drop down of downloads");
		Assert.assertEquals(a9, "fileDeckBandwidthDownloadSpeedInput");
		test.pass(a9);
		test.info("Select the GBytes/s in the drop down of downloads");
		Assert.assertEquals(a10, "                                                        Bytes/s\n"
				+ "                                                        kBytes/s\n"
				+ "                                                        MBytes/s\n"
				+ "                                                        GBytes/s\n"
				+ "                                                    ");
		test.pass(a10);
		Assert.assertEquals(a11, "GBytes/s");
		test.pass(a11);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on filedeck icon");
		Assert.assertEquals(a, "filemanager");
		test.pass(a);
		Assert.assertEquals(a1, "display: block;");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should select GBytes/s & It should enter the data in downloads");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting GBytes/s & It is entering the data in downloads");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[5]/span[2]")).getText();
		String a8=driver.findElement(By.xpath("(//span[@class='control-type-heading'])[2]")).getText();
		String a9=driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).sendKeys("10");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='fileDeckBandwidthUploadUnit']")).click();
		String a10=driver.findElement(By.xpath("//select[@id='fileDeckBandwidthUploadUnit']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//option[@value='b'])[2]")).click();
		String a11=driver.findElement(By.xpath("(//option[@value='b'])[2]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-app='filemanager']")).getAttribute("data-app");
		driver.findElement(By.xpath("//div[@data-app='filemanager']")).click();
		String a1=driver.findElement(By.xpath("//div[@style='display: block;']")).getAttribute("style");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("In upload, Enter the data & Select the Bytes/s");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("Click on Bandwidth controls");
		Assert.assertEquals(a7, "Bandwidth controls");
		test.pass(a7);
		test.info("In upload, Enter the value");
		Assert.assertEquals(a8, "Upload");
		test.pass(a8);
		test.info("Click on drop down of uploads");
		Assert.assertEquals(a9, "fileDeckBandwidthUploadSpeedInput");
		test.pass(a9);
		test.info("Select the Bytes/s in the drop down of upload");
		Assert.assertEquals(a10, "                                                        Bytes/s\n"
				+ "                                                        kBytes/s\n"
				+ "                                                        MBytes/s\n"
				+ "                                                        GBytes/s\n"
				+ "                                                    ");
		test.pass(a10);
		Assert.assertEquals(a11, "Bytes/s");
		test.pass(a11);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on filedeck icon");
		Assert.assertEquals(a, "filemanager");
		test.pass(a);
		Assert.assertEquals(a1, "display: block;");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should select Bytes/s & It should enter the data in upload");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting Bytes/s & It is entering the data in upload");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test09() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[5]/span[2]")).getText();
		String a8=driver.findElement(By.xpath("(//span[@class='control-type-heading'])[2]")).getText();
		String a9=driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).clear();
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).sendKeys("10");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='fileDeckBandwidthUploadUnit']")).click();
		String a10=driver.findElement(By.xpath("//select[@id='fileDeckBandwidthUploadUnit']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//option[@value='k'])[2]")).click();
		String a11=driver.findElement(By.xpath("(//option[@value='k'])[2]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-app='filemanager']")).getAttribute("data-app");
		driver.findElement(By.xpath("//div[@data-app='filemanager']")).click();
		String a1=driver.findElement(By.xpath("//div[@style='display: block;']")).getAttribute("style");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("In upload, Enter the data & Select the kBytes/s");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("Click on Bandwidth controls");
		Assert.assertEquals(a7, "Bandwidth controls");
		test.pass(a7);
		test.info("In upload, Enter the value");
		Assert.assertEquals(a8, "Upload");
		test.pass(a8);
		test.info("Click on drop down of uploads");
		Assert.assertEquals(a9, "fileDeckBandwidthUploadSpeedInput");
		test.pass(a9);
		test.info("Select the kBytes/s in the drop down of upload");
		Assert.assertEquals(a10, "                                                        Bytes/s\n"
				+ "                                                        kBytes/s\n"
				+ "                                                        MBytes/s\n"
				+ "                                                        GBytes/s\n"
				+ "                                                    ");
		test.pass(a10);
		Assert.assertEquals(a11, "kBytes/s");
		test.pass(a11);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on filedeck icon");
		Assert.assertEquals(a, "filemanager");
		test.pass(a);
		Assert.assertEquals(a1, "display: block;");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should select kBytes/s & It should enter the data in upload");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting kBytes/s & It is entering the data in upload");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test10() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[5]/span[2]")).getText();
		String a8=driver.findElement(By.xpath("(//span[@class='control-type-heading'])[2]")).getText();
		String a9=driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).clear();
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).sendKeys("10");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='fileDeckBandwidthUploadUnit']")).click();
		String a10=driver.findElement(By.xpath("//select[@id='fileDeckBandwidthUploadUnit']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//option[@value='M'])[2]")).click();
		String a11=driver.findElement(By.xpath("(//option[@value='M'])[2]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-app='filemanager']")).getAttribute("data-app");
		driver.findElement(By.xpath("//div[@data-app='filemanager']")).click();
		String a1=driver.findElement(By.xpath("//div[@style='display: block;']")).getAttribute("style");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("In upload, Enter the data & Select the MBytes/s");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("Click on Bandwidth controls");
		Assert.assertEquals(a7, "Bandwidth controls");
		test.pass(a7);
		test.info("In upload, Enter the value");
		Assert.assertEquals(a8, "Upload");
		test.pass(a8);
		test.info("Click on drop down of uploads");
		Assert.assertEquals(a9, "fileDeckBandwidthUploadSpeedInput");
		test.pass(a9);
		test.info("Select the MBytes/s in the drop down of upload");
		Assert.assertEquals(a10, "                                                        Bytes/s\n"
				+ "                                                        kBytes/s\n"
				+ "                                                        MBytes/s\n"
				+ "                                                        GBytes/s\n"
				+ "                                                    ");
		test.pass(a10);
		Assert.assertEquals(a11, "MBytes/s");
		test.pass(a11);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on filedeck icon");
		Assert.assertEquals(a, "filemanager");
		test.pass(a);
		Assert.assertEquals(a1, "display: block;");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should select MBytes/s & It should enter the data in upload");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting MBytes/s & It is entering the data in upload");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test11() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[5]/span[2]")).getText();
		String a8=driver.findElement(By.xpath("(//span[@class='control-type-heading'])[2]")).getText();
		String a9=driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).clear();
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).sendKeys("10");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='fileDeckBandwidthUploadUnit']")).click();
		String a10=driver.findElement(By.xpath("//select[@id='fileDeckBandwidthUploadUnit']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//option[@value='G'])[2]")).click();
		String a11=driver.findElement(By.xpath("(//option[@value='G'])[2]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		String a=driver.findElement(By.xpath("//div[@data-app='filemanager']")).getAttribute("data-app");
		driver.findElement(By.xpath("//div[@data-app='filemanager']")).click();
		String a1=driver.findElement(By.xpath("//div[@style='display: block;']")).getAttribute("style");
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("In upload, Enter the data & Select the GBytes/s");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("Click on Bandwidth controls");
		Assert.assertEquals(a7, "Bandwidth controls");
		test.pass(a7);
		test.info("In upload, Enter the value");
		Assert.assertEquals(a8, "Upload");
		test.pass(a8);
		test.info("Click on drop down of uploads");
		Assert.assertEquals(a9, "fileDeckBandwidthUploadSpeedInput");
		test.pass(a9);
		test.info("Select the GBytes/s in the drop down of upload");
		Assert.assertEquals(a10, "                                                        Bytes/s\n"
				+ "                                                        kBytes/s\n"
				+ "                                                        MBytes/s\n"
				+ "                                                        GBytes/s\n"
				+ "                                                    ");
		test.pass(a10);
		Assert.assertEquals(a11, "GBytes/s");
		test.pass(a11);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on filedeck icon");
		Assert.assertEquals(a, "filemanager");
		test.pass(a);
		Assert.assertEquals(a1, "display: block;");
		test.pass(a1);
		test.info("EXPECTED RESULT ::  It should select GBytes/s & It should enter the data in upload");
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is selecting GBytes/s & It is entering the data in upload");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test12() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[5]/span[2]")).getText();
		String a16=driver.findElement(By.xpath("//span[@class='control-type-heading']")).getText();
		String a17=driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthDownloadSpeedInput']")).sendKeys("10");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='fileDeckBandwidthDownloadUnit']")).click();
		String a18=driver.findElement(By.xpath("//select[@id='fileDeckBandwidthDownloadUnit']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//option[@value='b']")).click();
		String a19=driver.findElement(By.xpath("//option[@value='b']")).getText();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("(//span[@class='control-type-heading'])[2]")).getText();
		String a9=driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).clear();
		driver.findElement(By.xpath("//input[@id='fileDeckBandwidthUploadSpeedInput']")).sendKeys("10");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//select[@id='fileDeckBandwidthUploadUnit']")).click();
		String a10=driver.findElement(By.xpath("//select[@id='fileDeckBandwidthUploadUnit']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//option[@value='G'])[2]")).click();
		String a11=driver.findElement(By.xpath("(//option[@value='G'])[2]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a13=driver.findElement(By.xpath("(//span[@class='control-type-heading'])[1]")).getText();
		driver.findElement(By.xpath("(//option[@value='G'])[1]")).click();
		String a1=driver.findElement(By.xpath("(//option[@value='G'])[1]")).getText();
		Thread.sleep(1000);
		String a14=driver.findElement(By.xpath("(//span[@class='control-type-heading'])[2]")).getText();
		driver.findElement(By.xpath("(//option[@value='G'])[2]")).click();
		String a12=driver.findElement(By.xpath("(//option[@value='G'])[2]")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Combination of bandwidth controls");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("Click on Bandwidth controls");
		Assert.assertEquals(a7, "Bandwidth controls");
		test.pass(a7);
		test.info("In download, Enter the value");
		Assert.assertEquals(a16, "Download");
		test.pass(a16);
		test.info("Click on drop down of download");
		Assert.assertEquals(a17, "fileDeckBandwidthDownloadSpeedInput");
		test.pass(a17);
		test.info("Select the Bytes/s in the drop down of download");
		Assert.assertEquals(a18, "                                                        Bytes/s\n"
				+ "                                                        kBytes/s\n"
				+ "                                                        MBytes/s\n"
				+ "                                                        GBytes/s\n"
				+ "                                                    ");
		test.pass(a18);
		Assert.assertEquals(a19, "Bytes/s");
		test.pass(a19);
		test.info("In upload, Enter the value");
		Assert.assertEquals(a8, "Upload");
		test.pass(a8);
		test.info("Click on drop down of uploads");
		Assert.assertEquals(a9, "fileDeckBandwidthUploadSpeedInput");
		test.pass(a9);
		test.info("Select the GBytes/s in the drop down of upload");
		Assert.assertEquals(a10, "                                                        Bytes/s\n"
				+ "                                                        kBytes/s\n"
				+ "                                                        MBytes/s\n"
				+ "                                                        GBytes/s\n"
				+ "                                                    ");
		test.pass(a10);
		Assert.assertEquals(a11, "GBytes/s");
		test.pass(a11);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on dashboard");
		test.info("Click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a, "FileDeck");
		test.pass(a);
		test.info("EXPECTED RESULT ::  It should display download with Bytes/s & Upload with GBytes/s");
		Assert.assertEquals(a13, "Download");
		test.pass(a13);
		Assert.assertEquals(a1, "GBytes/s");
		test.pass(a1);
		Assert.assertEquals(a14, "Upload");
		test.pass(a14);
		Assert.assertEquals(a12, "GBytes/s");
		test.pass(a12);
		test.log(Status.FAIL ,"ACTUAL RESULT ::  It is displaying both download & upload with GBytes/s");
		test.pass("Test Case:: TestCase FAILED");
		driver.close();
	}
	@Test
	public void test13() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[7]/span[2]")).getText();
		String a8=driver.findElement(By.xpath("(//span[@class='control-type-heading'])[3]")).getText();
		String a9=driver.findElement(By.xpath("//input[@id='fileDeckServerPortNumberInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckServerPortNumberInput']")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Clear the port number");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("Go near to port number");
		Assert.assertEquals(a7, "Server PORT");
		test.pass(a7);
		Assert.assertEquals(a8, "Port Number");
		test.pass(a8);
		Assert.assertEquals(a9, "fileDeckServerPortNumberInput");
		test.pass(a9);
		test.info("Clear the port number");
		test.info("click on save button");
		test.info("EXPECTED RESULT ::  It should clear the port number & save the filedeck");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is clearing the port number & saving the filedeck");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test14() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[7]/span[2]")).getText();
		String a8=driver.findElement(By.xpath("(//span[@class='control-type-heading'])[3]")).getText();
		String a9=driver.findElement(By.xpath("//input[@id='fileDeckServerPortNumberInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckServerPortNumberInput']")).clear();
		driver.findElement(By.xpath("//input[@id='fileDeckServerPortNumberInput']")).sendKeys("abc");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter the port number with alphabets");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("Go near to port number");
		Assert.assertEquals(a7, "Server PORT");
		test.pass(a7);
		Assert.assertEquals(a8, "Port Number");
		test.pass(a8);
		Assert.assertEquals(a9, "fileDeckServerPortNumberInput");
		test.pass(a9);
		test.info("Clear the port number");
		test.info("Enter the port number with alphabets : abc");
		test.info("click on save button");
		test.info("EXPECTED RESULT ::  It should display error msg");
		Assert.assertEquals(actual, "Invalid value for 'Port Number'");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying error msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test15() throws InterruptedException, IOException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionFeaturesSearch']")).sendKeys("file");
		String a4=driver.findElement(By.xpath("//div[@data-value='FileDeck']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='FileDeck']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[1]/span[2]")).getText();
		String a5=driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckFeatureRadioEnable']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[3]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionFileDeckSyncRadioEnable']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[11]/div[2]/div[1]/div[7]/span[2]")).getText();
		String a8=driver.findElement(By.xpath("(//span[@class='control-type-heading'])[3]")).getText();
		String a9=driver.findElement(By.xpath("//input[@id='fileDeckServerPortNumberInput']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='fileDeckServerPortNumberInput']")).clear();
		driver.findElement(By.xpath("//input[@id='fileDeckServerPortNumberInput']")).sendKeys("9005");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"fileDeckSaveBtn\"]")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Enter the port number with numeric");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on Filedeck");
		Assert.assertEquals(a4, "FileDeck");
		test.pass(a4);
		Assert.assertEquals(a2, "Feature");
		test.pass(a2);
		test.info("click on Enable button");
		Assert.assertEquals(a5, "Enable");
		test.pass(a5);
		test.info("Click on Sync");
		Assert.assertEquals(a3, "Sync");
		test.pass(a3);
		test.info("click on Enable button");
		Assert.assertEquals(a6, "Enable");
		test.pass(a6);
		test.info("Go near to port number");
		Assert.assertEquals(a7, "Server PORT");
		test.pass(a7);
		Assert.assertEquals(a8, "Port Number");
		test.pass(a8);
		Assert.assertEquals(a9, "fileDeckServerPortNumberInput");
		test.pass(a9);
		test.info("Clear the port number");
		test.info("Enter port number : 9005");
		test.info("click on save button");
		test.info("EXPECTED RESULT ::  It should enter the port number & save the filedeck");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is entering the port number & saving the filedeck");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
