package grit_controls;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class indicatorandmarker {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("indicator.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[6]/span")).click();
		driver.findElement(By.xpath("  //*[@id=\"forwardEnable\"]")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/input")).click();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='Global']")).click();
		Thread.sleep(1000);
		WebElement s = driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[3]/div[1]/div[10]/div/div/div[18]/div[5]/div/div[2]"));
		Actions a=new Actions(driver);
		a.moveToElement(s).contextClick().perform();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/nav/ul/li[3]/a"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		driver.findElement(By.xpath("//div[@data-username='sharath']")).click();
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("ForwardEnable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on indicator & markers");
		test.info("click on Forward Enable button");
		test.info("click on save");
		test.info("GoTo chat");
		test.info("Select on anyuser");
		test.info("Select any message and Click on Forward");
		test.info("Select any users and click on send button");
		test.info("EXPECTED RESULT ::  System should display forward symbol");
		test.log(Status.PASS ,"ACTUAL RESULT ::  updated!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test1() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[6]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"forwardDisable\"]")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/input")).click();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='Global']")).click();
		Thread.sleep(1000);
		WebElement s = driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[3]/div[1]/div[10]/div/div/div[18]/div[5]/div/div[2]"));
		Actions a=new Actions(driver);
		a.moveToElement(s).contextClick().perform();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("/html/body/div[1]/div[1]/nav/ul/li[3]/a"));
		Actions ac=new Actions(driver);
		ac.click(e).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		driver.findElement(By.xpath("//div[@data-username='sharath']")).click();
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("ForwardDisable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:abcd@gmail.com");
		test.info("Password:sai@123");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on indicator & markers");
		test.info("click on Forward Disable button");
		test.info("click on save");
		test.info("GoTo chat");
		test.info("Select on anyuser");
		test.info("Select the message and click on Forward");
		test.info("Select any user and click on send button");
		test.info("EXPECTED RESULT ::  System should not display forward symbol");
		test.log(Status.PASS ,"ACTUAL RESULT ::  updated!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test2() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[6]/span")).click();
		driver.findElement(By.xpath("  //*[@id=\"forkoutEnable\"]\n")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/input")).click();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='Global']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("hi");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		driver.findElement(By.xpath("//div[@data-username='maneesh']")).click();
		driver.findElement(By.xpath("//*[@id=\"sendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("ForkoutEnable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on indicator & markers");
		test.info("click on Forkout Enable button");
		test.info("click on save");
		test.info("GoTo chat");
		test.info("Select anyuser");
		test.info("type the message");
		test.info("Click on forkout option");
		test.info("Select any user in forkout option");
		test.info("click on send button");
		test.info("click on another user the message should be with forkout symbol");
		test.info("EXPECTED RESULT ::  System should display forkout symbol");
		test.log(Status.PASS ,"ACTUAL RESULT ::  updated!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test3() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[6]/span")).click();
		driver.findElement(By.xpath("  //*[@id=\"forkoutDisable\"]\n")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/input")).click();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='Global']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("hi");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='input-forkout-btn input-action-btn']")).click();
		driver.findElement(By.xpath("//div[@data-username='maneesh']")).click();
		driver.findElement(By.xpath("//*[@id=\"sendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("ForkoutDisable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on indicator & markers");
		test.info("click on Forkout Disable button");
		test.info("click on save");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("type the message");
		test.info("Click on forkout option");
		test.info("Select any user in forkout option");
		test.info("click on send button");
		test.info("click on another user the message should be without forkout symbol");
		test.info("EXPECTED RESULT ::  System should not display forkout symbol");
		test.log(Status.PASS ,"ACTUAL RESULT :: updated!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test4() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[6]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"typingEnable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/input")).click();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='Global']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("hi");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("TypingEnable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on indicator & markers");
		test.info("click on Typing Enable button");
		test.info("click on save");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("type the message");
		test.info("EXPECTED RESULT ::  System should display Typing");
		test.log(Status.PASS ,"ACTUAL RESULT ::  updated!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test5() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[6]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"typingDisable\"]")).click();
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/input")).click();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='Global']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("hi");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("TypingDisable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on indicator & markers");
		test.info("click on Typing Disable button");
		test.info("click on save");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("type the message");
		test.info("EXPECTED RESULT ::  System should not display Typing");
		test.log(Status.PASS ,"ACTUAL RESULT ::  updated!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test6() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[6]/span")).click();
		driver.findElement(By.xpath("  //*[@id=\"lastSeenEnable\"]")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/input")).click();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='Global']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("hi");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"sendMessageBtn\"]\n")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("global");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("LastseenEnable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on indicator & markers");
		test.info("click on Lastseen Enable button");
		test.info("click on save");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("type the message");
		test.info("Click on Logout");
		test.info("Login into another user");
		test.info("click on user");
		test.info("EXPECTED RESULT ::  System should display Lastseen");
		test.log(Status.PASS ,"ACTUAL RESULT ::  updated!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test7() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[6]/span")).click();
		driver.findElement(By.xpath("  //*[@id=\"lastSeenDisable\"]")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/input")).click();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='Global']")).click();
		driver.findElement(By.xpath("//span[@class='message-input']")).sendKeys("hi");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"sendMessageBtn\"]\n")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("global");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		driver.findElement(By.xpath("//div[@data-name='sharath']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("LastseenDisable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on indicator & markers");
		test.info("click on lastseen disable button");
		test.info("click on save");
		test.info("GoTo chat");
		test.info("Click on anyuser");
		test.info("type the message");
		test.info("Click on logout");
		test.info("login into another user");
		test.info("click on user");
		test.info("EXPECTED RESULT ::  System should not display Lastseen");
		test.log(Status.PASS ,"ACTUAL RESULT ::  updated!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test8() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[6]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"employeeLabelEnable\"]")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/input")).click();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Employee Label Enable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on indicator & markers");
		test.info("click on Employee Label enable button");
		test.info("click on save");
		test.info("GoTo chat");
		test.info("Click on particular user who has Employee label");
		test.info("EXPECTED RESULT ::  System should display Employee Label");
		test.log(Status.PASS ,"ACTUAL RESULT ::  updated!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test9() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Documents/chrome/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//div[@class='submit-wrap']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/span[1]")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[6]/span")).click();
		driver.findElement(By.xpath(" //*[@id=\"employeeLabelDisable\"]")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/input")).click();
		driver.navigate().refresh();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='maneesh']")).click();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Employee Label Enable");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:sharath");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on indicator & markers");
		test.info("click on Employee Label disable button");
		test.info("click on save");
		test.info("GoTo chat");
		test.info("Click on particular user who has Employee label");
		test.info("EXPECTED RESULT ::  System should not display Employee Label");
		test.log(Status.PASS ,"ACTUAL RESULT ::  updated!");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
