package grit_controls;

import java.io.IOException;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class MiscellaneousforGroup {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("MiscellaneousforGroup.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[2]")).getText();
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[1]/span[2]")).getText();
		String a=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousExitGroupsRadioDisable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMiscellaneousExitGroupsRadioDisable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[27]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String a4=driver.switchTo().alert().getText();
		driver.switchTo().alert().accept();
		Thread.sleep(500);
		Thread.sleep(2000);
		String a6=driver.findElement(By.xpath("//input[@id='recentUserSearch']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='recent-users-search-filter-text hidden']")).getAttribute("class");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Miscellaneous group with hide in exited/deleted group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on groups tab");
		Assert.assertEquals(a1, "Groups");
		test.pass(a1);
		test.info("Click on radio button of hide");
		Assert.assertEquals(a3, "Exited / Deleted groups");
		test.pass(a3);
		Assert.assertEquals(a, "Hide");
		test.pass(a);
		test.info("click on save button");
		Assert.assertEquals(a4, "Tm-Admin updated chat permissions.Reloading Browser..!");
		test.pass(a4);
		test.info("GoTo chat");
		test.info("Click on recent chat search");
		Assert.assertEquals(a6, "recentUserSearch");
		test.pass(a6);
		test.info("Click on all members & groups icon");
		test.info("EXPECTED RESULT ::  It should not display deleted/Exited groups");
		Assert.assertEquals(a2, "recent-users-search-filter-text hidden");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying deleted/Exited groups");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[2]")).getText();
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[1]/span[2]")).getText();
		String a=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousExitGroupsRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMiscellaneousExitGroupsRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[27]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String a4=driver.switchTo().alert().getText();
		driver.switchTo().alert().accept();
		Thread.sleep(500);
		Thread.sleep(2000);
		String a6=driver.findElement(By.xpath("//input[@id='recentUserSearch']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='recentUserSearch']")).click();
		Thread.sleep(500);
		driver.findElement(By.xpath("//div[@class='recent-users-search-filter-container active']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("(//div[@class='recent-users-search-filter-text'])[5]")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Miscellaneous group with show in exited/deleted group");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on groups tab");
		Assert.assertEquals(a1, "Groups");
		test.pass(a1);
		test.info("Click on radio button of show");
		Assert.assertEquals(a3, "Exited / Deleted groups");
		test.pass(a3);
		Assert.assertEquals(a, "Show");
		test.pass(a);
		test.info("click on save button");
		Assert.assertEquals(a4, "Tm-Admin updated chat permissions.Reloading Browser..!");
		test.pass(a4);
		test.info("GoTo chat");
		test.info("Click on recent chat search");
		Assert.assertEquals(a6, "recentUserSearch");
		test.pass(a6);
		test.info("Click on all members & groups icon");
		test.info("EXPECTED RESULT ::  It should display deleted/Exited groups");
		Assert.assertEquals(a2, "Deleted/Exit Groups");
		test.pass(a2);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying deleted/Exited groups");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[2]")).getText();
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[3]/span[2]")).getText();
		String a=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousGroupsHistoryRadioDisable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMiscellaneousGroupsHistoryRadioDisable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[27]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='Recall group']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='group-profile-tab']")).getText();
		driver.findElement(By.xpath("//div[@class='group-profile-tab']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='groupOldChatHistoryBtn']")).getAttribute("id");
		String a4=driver.findElement(By.xpath("//div[@id='groupOldChatHistoryBtn']")).getAttribute("class");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Miscellaneous group with disallow in chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email:android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on groups tab");
		Assert.assertEquals(a6, "Groups");
		test.pass(a6);
		test.info("Click on radio button of disallow in chat history");
		Assert.assertEquals(a3, "Group Chat History for new members");
		test.pass(a3);
		Assert.assertEquals(a, "Disallow");
		test.pass(a);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on recent chat search");
		test.info("Click on group");
		test.info("Click on profile");
		test.info("Click on logs");
		test.info("EXPECTED RESULT ::  It should not display chat history");
		Assert.assertEquals(a2, "Logs");
		test.pass(a2);
		Assert.assertEquals(a1, "groupOldChatHistoryBtn");
		test.pass(a1);
		Assert.assertEquals(a4, "hidden");
		test.pass(a4);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not displaying chat history");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[2]")).getText();
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[3]/span[2]")).getText();
		String a=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousGroupsHistoryRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMiscellaneousGroupsHistoryRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[27]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-name='Recall group']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='chatUserImage']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='group-profile-tab']")).getText();
		driver.findElement(By.xpath("//div[@class='group-profile-tab']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='groupOldChatHistoryBtn']")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Miscellaneous group with allow in chat history");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Email: android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on groups tab");
		Assert.assertEquals(a6, "Groups");
		test.pass(a6);
		test.info("Click on radio button of allow");
		Assert.assertEquals(a3, "Group Chat History for new members");
		test.pass(a3);
		Assert.assertEquals(a, "Allow");
		test.pass(a);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("GoTo chat");
		test.info("Click on recent chat search");
		test.info("Click on group");
		test.info("Click on profile");
		test.info("Click on logs");
		test.info("EXPECTED RESULT ::  It should display chat history");
		Assert.assertEquals(a2, "Logs");
		test.pass(a2);
		Assert.assertEquals(a1, "Chat History");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is displaying chat history");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[2]")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[5]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[1]/span")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/input")).getAttribute("placeholder");
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[1]/div/div[1]/input")).sendKeys("akhil");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@data-search='Akhil']")).getAttribute("data-search");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("##Members## Export data search with valid username");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on groups tab");
		Assert.assertEquals(a3, "Groups");
		test.pass(a3);
		test.info("Click on search in export data");
		Assert.assertEquals(a, "Who can export data");
		test.pass(a);
		Assert.assertEquals(a6, "Members");
		test.pass(a6);
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		test.info("Enter valid username");
		test.info("EXPECTED RESULT ::  It should display valid username");
		Assert.assertEquals(a2, "Akhil");
		test.pass(a2);
		test.info("ACTUAL RESULT ::  It is displaying valid username");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[2]")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[5]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[1]/span")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/input")).getAttribute("placeholder");
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[1]/div/div[1]/input")).sendKeys("asdsad");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='no-results-found']")).getAttribute("class");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("##Members## Export data search with invalid username");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on groups tab");
		Assert.assertEquals(a3, "Groups");
		test.pass(a3);
		test.info("Click on search in export data");
		Assert.assertEquals(a, "Who can export data");
		test.pass(a);
		Assert.assertEquals(a6, "Members");
		test.pass(a6);
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		test.info("Enter invalid username");
		test.info("EXPECTED RESULT ::  It should display no result found");
		Assert.assertEquals(a2, "no-results-found");
		test.pass(a2);
		test.info("ACTUAL RESULT ::  It is displaying no results found");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[2]")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[5]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[1]/span")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/input")).getAttribute("placeholder");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[1]/div/div[1]/span[2]")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("##Members## Export data in users count");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on groups tab");
		Assert.assertEquals(a3, "Groups");
		test.pass(a3);
		test.info("Click on search in export data");
		Assert.assertEquals(a, "Who can export data");
		test.pass(a);
		Assert.assertEquals(a6, "Members");
		test.pass(a6);
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		test.info("View the count of the users");
		test.info("EXPECTED RESULT ::  It should display count of the users");
		Assert.assertEquals(a2, "18");
		test.pass(a2);
		test.info("ACTUAL RESULT ::  It is displaying count of the users");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[2]")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[5]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/span")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/div/div[1]/input")).getAttribute("placeholder");
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/div/div[1]/input")).sendKeys("akshay");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@data-search='Akshay']")).getAttribute("data-search");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Users who can export Group (Messages/Data) search with valid username");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on groups tab");
		Assert.assertEquals(a3, "Groups");
		test.pass(a3);
		test.info("Click on search in export data");
		Assert.assertEquals(a, "Who can export data");
		test.pass(a);
		Assert.assertEquals(a6, "Users who can export Group (Messages/Data)");
		test.pass(a6);
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		test.info("Enter valid username");
		test.info("EXPECTED RESULT ::  It should display valid username");
		Assert.assertEquals(a2, "Akshay");
		test.pass(a2);
		test.info("ACTUAL RESULT ::  It is displaying valid username");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[2]")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[5]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/span")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/div/div[1]/input")).getAttribute("placeholder");
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/div/div[1]/input")).sendKeys("dsfasdf");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='no-results-found']")).getAttribute("class");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Users who can export Group (Messages/Data) search with invalid username");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on groups tab");
		Assert.assertEquals(a3, "Groups");
		test.pass(a3);
		test.info("Click on search in export data");
		Assert.assertEquals(a, "Who can export data");
		test.pass(a);
		Assert.assertEquals(a6, "Users who can export Group (Messages/Data)");
		test.pass(a6);
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		test.info("Enter invalid username");
		test.info("EXPECTED RESULT ::  It should display no result found");
		Assert.assertEquals(a2, "no-results-found");
		test.pass(a2);
		test.info("ACTUAL RESULT ::  It is displaying no results found");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[2]")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[5]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/span")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/div/div[1]/input")).getAttribute("placeholder");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/div/div[1]/span[3]")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Users who can export Group (Messages/Data) in users count");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on groups tab");
		Assert.assertEquals(a3, "Groups");
		test.pass(a3);
		test.info("Click on search in export data");
		Assert.assertEquals(a, "Who can export data");
		test.pass(a);
		Assert.assertEquals(a6, "Users who can export Group (Messages/Data)");
		test.pass(a6);
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		test.info("View the count of the users");
		test.info("EXPECTED RESULT ::  It should display count of the users");
		Assert.assertEquals(a2, "1");
		test.pass(a2);
		test.info("ACTUAL RESULT ::  It is displaying count of the users");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[2]")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[5]/span[2]")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[1]/span")).getText();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[1]/div/div[1]/span[2]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[1]/div/div[2]/div[3]/span[2]")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/span")).getText();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/div/div[1]/span[3]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[27]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("(//div[@class='group-option'])[7]")).getText();
		driver.findElement(By.xpath("(//div[@class='group-option'])[7]")).click();
		Thread.sleep(1000);
		String a9=driver.findElement(By.xpath("//input[@id='excelDateRangeFrom']")).getAttribute("id");
		driver.findElement(By.xpath("//input[@id='excelDateRangeFrom']")).click();
		driver.findElement(By.xpath("(//td[@class='day'])[1]")).click();
		Thread.sleep(1000);
		String a10=driver.findElement(By.xpath("//input[@id='excelDateRangeTo']")).getAttribute("id");
		driver.findElement(By.xpath("(//td[@class='day'])[9]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='downloadExcelChat']")).click();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		String a13=driver.findElement(By.xpath("(//div[@class='group-option'])[8]")).getText();
		driver.findElement(By.xpath("(//div[@class='group-option'])[8]")).click();
		Thread.sleep(1000);
		String a12=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Export the data into excel sheet");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on groups tab");
		Assert.assertEquals(a3, "Groups");
		test.pass(a3);
		test.info("View the count of the users");
		Assert.assertEquals(a, "Who can export data");
		test.pass(a);
		Assert.assertEquals(a1, "Members");
		test.pass(a1);
		Assert.assertEquals(a2, "18");
		test.pass(a2);
		Assert.assertEquals(a6, "Users who can export Group (Messages/Data)");
		test.pass(a6);
		Assert.assertEquals(a4, "2");
		test.pass(a4);
		test.info("Click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("Click on groups tab");
		test.info("Select any group");
		test.info("Click on 3 dots");
		test.info("Click on export chat & export group members");
		test.info("EXPECTED RESULT ::  It should export the data into excel sheet");
		Assert.assertEquals(a8, "Export Chat To Excel");
		test.pass(a8);
		Assert.assertEquals(a9, "excelDateRangeFrom");
		test.pass(a9);
		Assert.assertEquals(a10, "excelDateRangeTo");
		test.pass(a10);
		Assert.assertEquals(a11, "Excel Downloaded Successfully");
		test.pass(a11);
		Assert.assertEquals(a13, "Export Group Members To Excel");
		test.pass(a13);
		Assert.assertEquals(a12, "Excel Downloaded Successfully");
		test.pass(a12);
		test.info("ACTUAL RESULT ::  It is exporting the data into excel sheet");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[2]")).getText();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[5]/span[2]")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[1]/span")).getText();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[1]/div/div[1]/span[2]")).getText();
		Thread.sleep(1000);
		String a14=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/div/div[2]/div[2]/span[3]")).getAttribute("class");
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/div/div[2]/div[2]/span[3]")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/span")).getText();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/div/div[1]/span[3]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[27]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("(//div[@class='group-option'])[7]")).getText();
		driver.findElement(By.xpath("(//div[@class='group-option'])[7]")).click();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='group-options-button']")).click();
		Thread.sleep(1000);
		String a13=driver.findElement(By.xpath("(//div[@class='group-option'])[8]")).getText();
		driver.findElement(By.xpath("(//div[@class='group-option'])[8]")).click();
		Thread.sleep(1000);
		String a12=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Remove the permission of myself in export data");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on groups tab");
		Assert.assertEquals(a3, "Groups");
		test.pass(a3);
		test.info("View the count of the users");
		Assert.assertEquals(a, "Who can export data");
		test.pass(a);
		Assert.assertEquals(a1, "Members");
		test.pass(a1);
		Assert.assertEquals(a2, "18");
		test.pass(a2);
		test.info("Remove the myself user");
		Assert.assertEquals(a6, "Users who can export Group (Messages/Data)");
		test.pass(a6);
		Assert.assertEquals(a14, "close-icon");
		test.pass(a14);
		Assert.assertEquals(a4, "1");
		test.pass(a4);
		test.info("Click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("Click on groups tab");
		test.info("Select any group");
		test.info("Click on 3 dots");
		test.info("Click on export chat & export group members");
		test.info("EXPECTED RESULT ::  It should not export the data into excel sheet");
		Assert.assertEquals(a8, "Export Chat To Excel");
		test.pass(a8);
		Assert.assertEquals(a11, "You don't have permissions to perform this action!");
		test.pass(a11);
		Assert.assertEquals(a13, "Export Group Members To Excel");
		test.pass(a13);
		Assert.assertEquals(a12, "You don't have permissions to perform this action!");
		test.pass(a12);
		test.info("ACTUAL RESULT ::  It is not exporting the data into excel sheet");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
