package grit_controls;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class MiscellaneousMobile {
	WebDriver driver;
	ExtentHtmlReporter HtmlReporter;
	ExtentReports extent;

	@BeforeSuite
	public void Starttest() {
		HtmlReporter = new ExtentHtmlReporter("MiscellaneousMobile.html");
		extent = new ExtentReports();
		extent.attachReporter(HtmlReporter);
	}
	@Test
	public void test00() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[1]/span[2]")).getText();
		String a1=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousPlaystoreRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMiscellaneousPlaystoreRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[1]/span[2]")).getText();
		String a9=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousPlaystoreRadioEnable']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on miscellaneous mobile with yes in playstore");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on mobile tab");
		Assert.assertEquals(a3, "Mobile");
		test.pass(a3);
		test.info("Click on radio button of yes in play store");
		Assert.assertEquals(a, "Restrict login from PlayStore App");
		test.pass(a);
		Assert.assertEquals(a1, "Yes");
		test.pass(a1);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("Refresh the page");
		test.info("Click on AdminDashboard again");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a6, "Miscellaneous");
		test.pass(a6);
		test.info("Click on mobile tab");
		Assert.assertEquals(a7, "Mobile");
		test.pass(a7);
		Assert.assertEquals(a8, "Restrict login from PlayStore App");
		test.pass(a8);
		test.info("EXPECTED RESULT ::  It should select the radio button of yes in playstore");
		Assert.assertEquals(a9, "Yes");
		test.pass(a9);
		test.info("ACTUAL RESULT ::  It is selecting the radio button of yes in playstore");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[1]/span[2]")).getText();
		String a1=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousPlaystoreRadioDisable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMiscellaneousPlaystoreRadioDisable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[1]/span[2]")).getText();
		String a9=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousPlaystoreRadioDisable']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("Click on miscellaneous mobile with no in playstore");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on mobile tab");
		Assert.assertEquals(a3, "Mobile");
		test.pass(a3);
		test.info("Click on radio button of no in play store");
		Assert.assertEquals(a, "Restrict login from PlayStore App");
		test.pass(a);
		Assert.assertEquals(a1, "No");
		test.pass(a1);
		test.info("Click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("Refresh the page");
		test.info("Click on AdminDashboard again");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a6, "Miscellaneous");
		test.pass(a6);
		test.info("Click on mobile tab");
		Assert.assertEquals(a7, "Mobile");
		test.pass(a7);
		Assert.assertEquals(a8, "Restrict login from PlayStore App");
		test.pass(a8);
		test.info("EXPECTED RESULT ::  It should select the radio button of no in playstore");
		Assert.assertEquals(a9, "No");
		test.pass(a9);
		test.info("ACTUAL RESULT ::  It is selecting the radio button of no in playstore");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[3]/span[2]")).getText();
		String a1=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousAppstoreRadioEnable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMiscellaneousAppstoreRadioEnable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[3]/span[2]")).getText();
		String a9=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousAppstoreRadioEnable']")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous mobile with yes in Appstore");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on mobile tab");
		Assert.assertEquals(a3, "Mobile");
		test.pass(a3);
		test.info("Click on radio button of yes in App store");
		Assert.assertEquals(a, "Restrict login from AppStore App");
		test.pass(a);
		Assert.assertEquals(a1, "Yes");
		test.pass(a1);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("Refresh the page");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a6, "Miscellaneous");
		test.pass(a6);
		test.info("Click on mobile tab");
		Assert.assertEquals(a7, "Mobile");
		test.pass(a7);
		Assert.assertEquals(a8, "Restrict login from AppStore App");
		test.pass(a8);
		test.info("EXPECTED RESULT ::  It should select the radio button of yes in Appstore");
		Assert.assertEquals(a9, "Yes");
		test.pass(a9);
		test.info("ACTUAL RESULT ::  It is selecting the radio button of yes in Appstore");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[3]/span[2]")).getText();
		String a1=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousAppstoreRadioDisable']")).getText();
		driver.findElement(By.xpath("//label[@for='permissionMiscellaneousAppstoreRadioDisable']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[3]/span[2]")).getText();
		String a9=driver.findElement(By.xpath("//label[@for='permissionMiscellaneousAppstoreRadioDisable']")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous mobile with no in Appstore");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on mobile tab");
		Assert.assertEquals(a3, "Mobile");
		test.pass(a3);
		test.info("Click on radio button of yes in App store");
		Assert.assertEquals(a, "Restrict login from AppStore App");
		test.pass(a);
		Assert.assertEquals(a1, "No");
		test.pass(a1);
		test.info("click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("Refresh the page");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a6, "Miscellaneous");
		test.pass(a6);
		test.info("Click on mobile tab");
		Assert.assertEquals(a7, "Mobile");
		test.pass(a7);
		Assert.assertEquals(a8, "Restrict login from AppStore App");
		test.pass(a8);
		test.info("EXPECTED RESULT ::  It should select the radio button of no in Appstore");
		Assert.assertEquals(a9, "No");
		test.pass(a9);
		test.info("ACTUAL RESULT ::  It is selecting the radio button of no in Appstore");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[6]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/span")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/input")).getAttribute("placeholder");
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/input")).sendKeys("sharath");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@data-search='sharath e2ee']")).getAttribute("data-search");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous mobile with Excluded search with valid username");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on mobile tab");
		Assert.assertEquals(a3, "Mobile");
		test.pass(a3);
		test.info("Click on search in excluded");
		Assert.assertEquals(a, "Who can be Excluded");
		test.pass(a);
		Assert.assertEquals(a6, "Members");
		test.pass(a6);
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		test.info("Enter valid username");
		test.info("EXPECTED RESULT ::  It should display valid username");
		Assert.assertEquals(a2, "sharath e2ee");
		test.pass(a2);
		test.info("ACTUAL RESULT ::  It is displaying valid username");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[6]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/span")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/input")).getAttribute("placeholder");
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/input")).sendKeys("sadasd");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='no-results-found']")).getAttribute("class");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous mobile with Excluded search with invalid username");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on mobile tab");
		Assert.assertEquals(a3, "Mobile");
		test.pass(a3);
		test.info("Click on search in excluded");
		Assert.assertEquals(a, "Who can be Excluded");
		test.pass(a);
		Assert.assertEquals(a6, "Members");
		test.pass(a6);
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		test.info("Enter invalid username");
		test.info("EXPECTED RESULT ::  It should display no result found");
		Assert.assertEquals(a2, "no-results-found");
		test.pass(a2);
		test.info("ACTUAL RESULT ::  It is displaying no results found");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[6]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/span")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/input")).getAttribute("placeholder");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/span[2]")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous mobile with Excluded users count");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on mobile tab");
		Assert.assertEquals(a3, "Mobile");
		test.pass(a3);
		test.info("Click on search in excluded");
		Assert.assertEquals(a, "Who can be Excluded");
		test.pass(a);
		Assert.assertEquals(a6, "Members");
		test.pass(a6);
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		test.info("View the count of the users");
		test.info("EXPECTED RESULT ::  It should display count of the users");
		Assert.assertEquals(a2, "94");
		test.pass(a2);
		test.info("ACTUAL RESULT ::  It is displaying count of the users");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[6]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/span")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/input")).getAttribute("placeholder");
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[2]/div[1]/span[2]")).click();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/div/div[1]/input")).sendKeys("akhil");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@data-search='Akhil']")).getAttribute("data-search");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous mobile with Excluded search with valid username");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on mobile tab");
		Assert.assertEquals(a3, "Mobile");
		test.pass(a3);
		test.info("Click on search in excluded");
		Assert.assertEquals(a, "Who can be Excluded");
		test.pass(a);
		Assert.assertEquals(a6, "Users who can be excluded from above permissions");
		test.pass(a6);
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		test.info("Enter valid username");
		test.info("EXPECTED RESULT ::  It should display valid username");
		Assert.assertEquals(a2, "Akhil");
		test.pass(a2);
		test.info("ACTUAL RESULT ::  It is displaying valid username");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[6]/span[2]")).getText();
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/span")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/input")).getAttribute("placeholder");
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/div/div[1]/input")).sendKeys("sadasd");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='no-results-found']")).getAttribute("class");
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous mobile with Excluded search with invalid username");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on mobile tab");
		Assert.assertEquals(a3, "Mobile");
		test.pass(a3);
		test.info("Click on search in excluded");
		Assert.assertEquals(a, "Who can be Excluded");
		test.pass(a);
		Assert.assertEquals(a6, "Users who can be excluded from above permissions");
		test.pass(a6);
		Assert.assertEquals(a1, "Search");
		test.pass(a1);
		test.info("Enter invalid username");
		test.info("EXPECTED RESULT ::  It should display no result found");
		Assert.assertEquals(a2, "no-results-found");
		test.pass(a2);
		test.info("ACTUAL RESULT ::  It is displaying no results found");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[6]/span[2]")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/span")).getText();
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/input")).getAttribute("placeholder");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/div/div[1]/span[3]")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous mobile with Excluded users count");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on mobile tab");
		Assert.assertEquals(a3, "Mobile");
		test.pass(a3);
		test.info("Click on search in excluded");
		Assert.assertEquals(a, "Who can be Excluded");
		test.pass(a);
		Assert.assertEquals(a1, "Users who can be excluded from above permissions");
		test.pass(a1);
		Assert.assertEquals(a6, "Search");
		test.pass(a6);
		test.info("View the count of the users");
		test.info("EXPECTED RESULT ::  It should display count of the users");
		Assert.assertEquals(a2, "0");
		test.pass(a2);
		test.info("ACTUAL RESULT ::  It is displaying count of the users");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[6]/span[2]")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/span")).getText();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/span[2]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[2]/div[1]/span[2]")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/span")).getText();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/div/div[1]/span[3]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a9=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/span")).getText();
		Thread.sleep(1000);
		String a10=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/span[2]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[2]/div[1]/span[2]")).click();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/span")).getText();
		Thread.sleep(1000);
		String a12=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/div/div[1]/span[3]")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous mobile with Excluded users count by adding user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on mobile tab");
		Assert.assertEquals(a3, "Mobile");
		test.pass(a3);
		test.info("View the count of the users");
		Assert.assertEquals(a, "Who can be Excluded");
		test.pass(a);
		Assert.assertEquals(a1, "Members");
		test.pass(a1);
		Assert.assertEquals(a2, "94");
		test.pass(a2);
		Assert.assertEquals(a6, "Users who can be excluded from above permissions");
		test.pass(a6);
		Assert.assertEquals(a4, "1");
		test.pass(a4);
		test.info("Click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("Click on refresh");
		test.info("Click on dashboard again");
		test.info("Click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a7, "Miscellaneous");
		test.pass(a7);
		test.info("Click on mobile tab");
		Assert.assertEquals(a8, "Mobile");
		test.pass(a8);
		test.info("View the count of who can be excluded");
		test.info("EXPECTED RESULT ::  It should add the users");
		Assert.assertEquals(a9, "Members");
		test.pass(a9);
		Assert.assertEquals(a10, "94");
		test.pass(a10);
		Assert.assertEquals(a11, "Users who can be excluded from above permissions");
		test.pass(a11);
		Assert.assertEquals(a12, "1");
		test.pass(a12);
		test.info("ACTUAL RESULT ::  It is adding the users");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[6]/span[2]")).getText();
		String a1=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/span")).getText();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/span[2]")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[2]/div[1]/span[2]")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/span")).getText();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/div/div[1]/span[3]")).getText();
		Thread.sleep(1000);
		String a13=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/div/div[2]/div/span[3]")).getAttribute("class");
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/div/div[2]/div/span[3]")).click();
		String a14=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/div/div[1]/span[3]")).getText();
		Thread.sleep(1000);
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[2]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).getAttribute("data-value");
		driver.findElement(By.xpath("//div[@data-value='Miscellaneous']")).click();
		Thread.sleep(1000);
		String a8=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).getText();
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[1]/div[3]")).click();
		Thread.sleep(1000);
		String a9=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/span")).getText();
		Thread.sleep(1000);
		String a10=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[1]/div/div[1]/span[2]")).getText();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/span")).getText();
		Thread.sleep(1000);
		String a12=driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div[27]/div[2]/div[1]/div[2]/div[3]/div/div[7]/div/div[2]/div/div[1]/span[3]")).getText();
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("Click on miscellaneous mobile with Excluded users count by removing user");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("Username : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a5, "Miscellaneous");
		test.pass(a5);
		test.info("Click on mobile tab");
		Assert.assertEquals(a3, "Mobile");
		test.pass(a3);
		Assert.assertEquals(a, "Who can be Excluded");
		test.pass(a);
		Assert.assertEquals(a1, "Members");
		test.pass(a1);
		Assert.assertEquals(a2, "94");
		test.pass(a2);
		Assert.assertEquals(a6, "Users who can be excluded from above permissions");
		test.pass(a6);
		Assert.assertEquals(a4, "1");
		test.pass(a4);
		test.info("Remove the selected user");
		Assert.assertEquals(a13, "close-icon");
		test.pass(a13);
		Assert.assertEquals(a14, "0");
		test.pass(a14);
		test.info("Click on save button");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		test.info("Click on refresh");
		test.info("Click on dashboard again");
		test.info("Click on controls");
		test.info("Click on miscellaneous");
		Assert.assertEquals(a7, "Miscellaneous");
		test.pass(a7);
		test.info("Click on mobile tab");
		Assert.assertEquals(a8, "Mobile");
		test.pass(a8);
		test.info("View the count of who can be excluded");
		test.info("EXPECTED RESULT ::  It should remove the users");
		Assert.assertEquals(a9, "Members");
		test.pass(a9);
		Assert.assertEquals(a10, "94");
		test.pass(a10);
		Assert.assertEquals(a11, "Users who can be excluded from above permissions");
		test.pass(a11);
		Assert.assertEquals(a12, "0");
		test.pass(a12);
		test.info("ACTUAL RESULT ::  It is removing the users");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
