package grit_controls;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class orangemember {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("orangemember.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test00() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on orange member in controls");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("EXPECTED RESULT:: It should display orange member page");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying orange member page");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='orangeMemberPermissionSettingsBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='header-text']")).getText();
		String a2=driver.findElement(By.xpath("//div[@class='permission-options-container']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on settings in orange member");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Click on settings button");
		test.info("EXPECTED RESULT:: It should click on settings in orange member");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a1, "Conditions");
		test.pass(a1);
		Assert.assertEquals(a2, "Can't be added into groups\n"
				+ "Can't see message info of other users\n"
				+ "Can't see Profile info of other users\n"
				+ "Replace Orange Dot with Light Orange");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on settings in orange member");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='orangeMemberPermissionSettingsBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='header-text']")).getText();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//span[@class='content-close-btn']")).getAttribute("class");
		driver.findElement(By.xpath("//span[@class='content-close-btn']")).click();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on close button in settings");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Click on settings button");
		test.info("Click on close button");
		test.info("EXPECTED RESULT:: It should click on close button in settings");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a1, "Conditions");
		test.pass(a1);
		Assert.assertEquals(a2, "content-close-btn");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on close button in settings");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='orangeMemberPermissionSettingsBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='header-text']")).getText();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//input[@value='Apply']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@value='Apply']")).click();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on apply button in settings without selecting any checkbox");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Click on settings button");
		test.info("Don't select any checkbox");
		test.info("Click on apply button");
		test.info("EXPECTED RESULT:: It should click on apply button in settings");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a1, "Conditions");
		test.pass(a1);
		Assert.assertEquals(a2, "Apply");
		test.pass(a2);
		String a3=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals(a3, "Conditions applied");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on apply button in settings");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='orangeMemberPermissionSettingsBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='header-text']")).getText();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//label[@for='orangeMemberPermissionCantAddedToGroupCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='orangeMemberPermissionCantAddedToGroupCheckbox']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//input[@value='Apply']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@value='Apply']")).click();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on apply button in settings with selecting any checkbox");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Click on settings button");
		test.info("Select any checkbox");
		test.info("Click on apply button");
		test.info("EXPECTED RESULT:: It should click on apply button in settings by selecting any checkbox");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a1, "Conditions");
		test.pass(a1);
		Assert.assertEquals(a2, "Apply");
		test.pass(a2);
		Assert.assertEquals(a4, "Can't be added into groups");
		test.pass(a4);
		String a3=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals(a3, "Conditions applied");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on apply button in settings by selecting any checkbox");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@id='orangeMemberPermissionSettingsBtn']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//span[@class='header-text']")).getText();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//label[@for='orangeMemberPermissionCantAddedToGroupCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='orangeMemberPermissionCantAddedToGroupCheckbox']")).click();
		Thread.sleep(1000);
		String a5=driver.findElement(By.xpath("//label[@for='orangeMemberPermissionCantSeeInfoCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='orangeMemberPermissionCantSeeInfoCheckbox']")).click();
		Thread.sleep(1000);
		String a6=driver.findElement(By.xpath("//label[@for='orangeMemberPermissionCantSeeProfileCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='orangeMemberPermissionCantSeeProfileCheckbox']")).click();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("//label[@for='orangeMemberPermissionOrangeDotCheckbox']")).getText();
		driver.findElement(By.xpath("//label[@for='orangeMemberPermissionOrangeDotCheckbox']")).click();
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//input[@value='Apply']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@value='Apply']")).click();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Click on apply button in settings with selecting all the checkbox");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Click on settings button");
		test.info("Select all the checkbox");
		test.info("Click on apply button");
		test.info("EXPECTED RESULT:: It should click on apply button in settings by selecting all the checkbox");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a1, "Conditions");
		test.pass(a1);
		Assert.assertEquals(a2, "Apply");
		test.pass(a2);
		Assert.assertEquals(a4, "Can't be added into groups");
		test.pass(a4);
		Assert.assertEquals(a5, "Can't see message info of other users");
		test.pass(a5);
		Assert.assertEquals(a6, "Can't see Profile info of other users");
		test.pass(a6);
		Assert.assertEquals(a7, "Replace Orange Dot with Light Orange");
		test.pass(a7);
		String a3=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals(a3, "Conditions applied");
		test.pass(a3);
		test.log(Status.PASS,"ACTUAL RESULT::  It is clicking on apply button in settings by selecting all the checkbox");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@class='selected-info-text']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("View the default permission");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("EXPECTED RESULT:: It should display the default permissions for orange member");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a1, "Default Permission Users can chat with all users , all orange users");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is displaying default permission for orange member");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='info-text']")).getText();
		driver.findElement(By.xpath("//div[@class='orange-switch-btn']")).click();
		String a1=driver.findElement(By.xpath("//div[@class='orange-switch-btn active']")).getAttribute("class");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("switch to orange member");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Switch to orange user");
		test.info("EXPECTED RESULT:: It should click on orange member icon");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Members");
		test.pass(a3);
		Assert.assertEquals(a1, "orange-switch-btn active");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is click on orange member icon");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='info-text']")).getText();
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).sendKeys("sharath");
		String a1=driver.findElement(By.xpath("//div[@data-search='sharath']")).getAttribute("data-search");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Search valid user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Click on search");
		test.info("Search valid user");
		test.info("EXPECTED RESULT:: It should search the username");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Members");
		test.pass(a3);
		Assert.assertEquals(a1, "sharath");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is searching the username");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='info-text']")).getText();
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).sendKeys("sadasf");
		String a1=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Search invalid user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Click on search");
		test.info("Search invalid user");
		test.info("EXPECTED RESULT:: It should not search the username");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Members");
		test.pass(a3);
		Assert.assertEquals(a1, "No results found!");
		test.pass(a1);
		test.log(Status.PASS,"ACTUAL RESULT::  It is not searching the username");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='info-text']")).getText();
		driver.findElement(By.xpath("//div[@class='orange-switch-btn']")).click();
		String a1=driver.findElement(By.xpath("//div[@class='orange-switch-btn active']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).sendKeys("sai");
		String a2=driver.findElement(By.xpath("//div[@data-search='Sai']")).getAttribute("data-search");
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("switch to orange member & Search the valid user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Switch to orange user");
		test.info("Click on search");
		test.info("Search valid username");
		test.info("EXPECTED RESULT:: It should search the valid orange member");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Members");
		test.pass(a3);
		Assert.assertEquals(a1, "orange-switch-btn active");
		test.pass(a1);
		Assert.assertEquals(a2, "Sai");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is searching the valid orange member");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='info-text']")).getText();
		driver.findElement(By.xpath("//div[@class='orange-switch-btn']")).click();
		String a1=driver.findElement(By.xpath("//div[@class='orange-switch-btn active']")).getAttribute("class");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id='permissionUsersSearchInput']")).sendKeys("sadf");
		String a2=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("switch to orange member & Search the invalid user");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Switch to orange user");
		test.info("Click on search");
		test.info("Search invalid username");
		test.info("EXPECTED RESULT:: It should not search the orange member");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Members");
		test.pass(a3);
		Assert.assertEquals(a1, "orange-switch-btn active");
		test.pass(a1);
		Assert.assertEquals(a2, "No results found!");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is not searching the orange member");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='info-text']")).getText();
		driver.findElement(By.xpath("//div[@data-search='123']")).click();
		String a1=driver.findElement(By.xpath("//div[@data-search='123']")).getAttribute("data-search");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='Akhil']")).click();
		String a4=driver.findElement(By.xpath("//div[@data-search='Akhil']")).getAttribute("data-search");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='Akshay']")).click();
		String a5=driver.findElement(By.xpath("//div[@data-search='Akshay']")).getAttribute("data-search");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='selected-info-text']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Select the users");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Select the users");
		test.info("EXPECTED RESULT:: It should select the users");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Members");
		test.pass(a3);
		Assert.assertEquals(a1, "123");
		test.pass(a1);
		Assert.assertEquals(a4, "Akhil");
		test.pass(a4);
		Assert.assertEquals(a5, "Akshay");
		test.pass(a5);
		Assert.assertEquals(a2, "Default Permission Users can chat with 3 users , all orange users");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is selecting the users");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='info-text']")).getText();
		driver.findElement(By.xpath("//div[@class='orange-switch-btn']")).click();
		String a1=driver.findElement(By.xpath("//div[@class='orange-switch-btn active']")).getAttribute("class");
		Thread.sleep(2000);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='anvesh']")).click();
		String a4=driver.findElement(By.xpath("//div[@data-search='anvesh']")).getAttribute("data-search");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='asif']")).click();
		String a6=driver.findElement(By.xpath("//div[@data-search='asif']")).getAttribute("data-search");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='selected-info-text']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Select the orange member");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Switch to orange user");
		test.info("Select the orange users");
		test.info("EXPECTED RESULT:: It should select the orange member");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Members");
		test.pass(a3);
		Assert.assertEquals(a1, "orange-switch-btn active");
		test.pass(a1);
		Assert.assertEquals(a6, "asif");
		test.pass(a6);
		Assert.assertEquals(a4, "anvesh");
		test.pass(a4);
		Assert.assertEquals(a2, "Default Permission Users can chat with all users , 2 orange users");
		test.pass(a2);
		test.log(Status.PASS,"ACTUAL RESULT::  It is selecting the orange member");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test14() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='Akhil']")).click();
		String a3=driver.findElement(By.xpath("(//span[@class='info-text'])[2]")).getText();
		driver.findElement(By.xpath("(//input[@class='form-control input-search'])[2]")).sendKeys("akhil");
		String a1=driver.findElement(By.xpath("(//input[@class='form-control input-search'])[2]")).getAttribute("class");
		Thread.sleep(2000);
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@data-search='Akhil']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Search the valid user in default permissions");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Click on search in default permissions");
		test.info("Search the valid username");
		test.info("EXPECTED RESULT:: It should search the user in default prermission");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Default Permission Users can chat with");
		test.pass(a3);
		Assert.assertEquals(a1, "form-control input-search");
		test.pass(a1);
		Assert.assertEquals(a4, "Akhil");
		test.pass(a4);
		test.log(Status.PASS,"ACTUAL RESULT::  It is searching the user in default prermission");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test15() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("(//span[@class='info-text'])[2]")).getText();
		driver.findElement(By.xpath("(//input[@class='form-control input-search'])[2]")).sendKeys("akhil");
		String a1=driver.findElement(By.xpath("(//input[@class='form-control input-search'])[2]")).getAttribute("class");
		Thread.sleep(2000);
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@class='no-results-found']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Search the valid user in default permissions");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Click on search in default permissions");
		test.info("Search the invalid username");
		test.info("EXPECTED RESULT:: It should not search the user in default prermission");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Default Permission Users can chat with");
		test.pass(a3);
		Assert.assertEquals(a1, "form-control input-search");
		test.pass(a1);
		Assert.assertEquals(a4, "No results found!");
		test.pass(a4);
		test.log(Status.PASS,"ACTUAL RESULT::  It is not searching the user in default prermission");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test16() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("(//span[@class='info-text'])[2]")).getText();
		driver.findElement(By.xpath("(//span[@class='close-icon'])[2]")).click();
		String a1=driver.findElement(By.xpath("(//span[@class='close-icon'])[2]")).getAttribute("class");
		Thread.sleep(2000);
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@class='selected-info-text']")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Search the valid user in default permissions");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Click on search in default permissions");
		test.info("Search the invalid username");
		test.info("EXPECTED RESULT:: It should not search the user in default prermission");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Default Permission Users can chat with");
		test.pass(a3);
		Assert.assertEquals(a1, "close-icon");
		test.pass(a1);
		Assert.assertEquals(a4, "Default Permission Users can chat with all users");
		test.pass(a4);
		test.log(Status.PASS,"ACTUAL RESULT::  It is not searching the user in default prermission");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test17() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("(//span[@class='info-text'])[2]")).getText();
		driver.findElement(By.xpath("(//span[@class='close-icon'])[2]")).click();
		String a1=driver.findElement(By.xpath("(//span[@class='close-icon'])[2]")).getAttribute("class");
		Thread.sleep(2000);
		String a5=driver.findElement(By.xpath("(//span[@class='close-icon'])[1]")).getAttribute("class");
		driver.findElement(By.xpath("(//span[@class='close-icon'])[1]")).click();
		Thread.sleep(1000);
		String a4=driver.findElement(By.xpath("//div[@class='selected-info-text']")).getText();
		Thread.sleep(1000);
		String a7=driver.findElement(By.xpath("//input[@id='userPermissionSubmitBtn']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@id='userPermissionSubmitBtn']")).click();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Search the valid user in default permissions");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Click on search in default permissions");
		test.info("Search the invalid username");
		test.info("EXPECTED RESULT:: It should deselect all the user in default prermission");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Default Permission Users can chat with");
		test.pass(a3);
		Assert.assertEquals(a1, "close-icon");
		test.pass(a1);
		Assert.assertEquals(a5, "close-icon");
		test.pass(a5);
		Assert.assertEquals(a4, "Default Permission Users can chat with");
		test.pass(a4);
		Assert.assertEquals(a7, "SAVE");
		test.pass(a7);
		String a6=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Assert.assertEquals(a6, "Please select atleast one user");
		test.pass(a6);
		test.log(Status.PASS,"ACTUAL RESULT::  It is deselecting all the user in default prermission");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test18() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='info-text']")).getText();
		driver.findElement(By.xpath("//div[@data-search='123']")).click();
		String a1=driver.findElement(By.xpath("//div[@data-search='123']")).getAttribute("data-search");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='Akhil']")).click();
		String a4=driver.findElement(By.xpath("//div[@data-search='Akhil']")).getAttribute("data-search");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='Akshay']")).click();
		String a5=driver.findElement(By.xpath("//div[@data-search='Akshay']")).getAttribute("data-search");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='orange-switch-btn']")).click();
		String a6=driver.findElement(By.xpath("//div[@class='orange-switch-btn active']")).getAttribute("class");
		Thread.sleep(2000);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='anvesh']")).click();
		String a7=driver.findElement(By.xpath("//div[@data-search='anvesh']")).getAttribute("data-search");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='asif']")).click();
		String a8=driver.findElement(By.xpath("//div[@data-search='asif']")).getAttribute("data-search");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='selected-info-text']")).getText();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("(//span[@class='user-count'])[2]")).getText();
		Thread.sleep(1000);
		String a9=driver.findElement(By.xpath("//input[@id='userPermissionSubmitBtn']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@id='userPermissionSubmitBtn']")).click();
		Thread.sleep(1000);
		String a10=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Select the users & orange members");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Select the users");
		test.info("Switch the button to orange member");
		test.info("Select the orange members");
		test.info("Click on save button");
		test.info("EXPECTED RESULT:: It should select the users & orange users");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Members");
		test.pass(a3);
		Assert.assertEquals(a1, "123");
		test.pass(a1);
		Assert.assertEquals(a4, "Akhil");
		test.pass(a4);
		Assert.assertEquals(a5, "Akshay");
		test.pass(a5);
		Assert.assertEquals(a6, "orange-switch-btn active");
		test.pass(a6);
		Assert.assertEquals(a7, "anvesh");
		test.pass(a7);
		Assert.assertEquals(a8, "asif");
		test.pass(a8);
		Assert.assertEquals(a2, "Default Permission Users can chat with 3 users , 2 orange users");
		test.pass(a2);
		Assert.assertEquals(a11, "5");
		test.pass(a11);
		Assert.assertEquals(a9, "SAVE");
		test.pass(a9);
		Assert.assertEquals(a10, "Permissions applied");
		test.pass(a10);
		test.log(Status.PASS,"ACTUAL RESULT::  It is selecting the users & orange users");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@Test
	public void test19() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083/user/login");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath1");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Orange Member']")).click();
		String a=driver.findElement(By.xpath("//div[@data-value='Orange Member']")).getAttribute("data-value");
		Thread.sleep(1000);
		String a3=driver.findElement(By.xpath("//span[@class='info-text']")).getText();
		driver.findElement(By.xpath("//div[@data-search='123']")).click();
		String a1=driver.findElement(By.xpath("//div[@data-search='123']")).getAttribute("data-search");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='Akhil']")).click();
		String a4=driver.findElement(By.xpath("//div[@data-search='Akhil']")).getAttribute("data-search");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='Akshay']")).click();
		String a5=driver.findElement(By.xpath("//div[@data-search='Akshay']")).getAttribute("data-search");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@class='orange-switch-btn']")).click();
		String a6=driver.findElement(By.xpath("//div[@class='orange-switch-btn active']")).getAttribute("class");
		Thread.sleep(2000);
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='anvesh']")).click();
		String a7=driver.findElement(By.xpath("//div[@data-search='anvesh']")).getAttribute("data-search");
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-search='asif']")).click();
		String a8=driver.findElement(By.xpath("//div[@data-search='asif']")).getAttribute("data-search");
		Thread.sleep(1000);
		String a2=driver.findElement(By.xpath("//div[@class='selected-info-text']")).getText();
		Thread.sleep(1000);
		String a11=driver.findElement(By.xpath("(//span[@class='user-count'])[2]")).getText();
		Thread.sleep(1000);
		String a9=driver.findElement(By.xpath("//input[@id='userPermissionSubmitBtn']")).getAttribute("value");
		driver.findElement(By.xpath("//input[@id='userPermissionSubmitBtn']")).click();
		Thread.sleep(1000);
		String a10=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		String a14=driver.findElement(By.xpath("//div[@class='default-permission-button']")).getText();
		driver.findElement(By.xpath("//div[@class='default-permission-button']")).click();
		Thread.sleep(1000);
		String a12=driver.findElement(By.xpath("//div[@class='selected-info-text']")).getText();
		Thread.sleep(1000);
		String a13=driver.findElement(By.xpath("(//span[@class='user-count'])[2]")).getText();
		Thread.sleep(1000);
		ExtentTest test = extent.createTest("Select the users & orange members");
		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL");
		test.info("Username : sharath1");
		test.info("Password: 123456");
		test.info("Login:Click on Login");
		test.info("Click on controls");
		test.info("Click on orange member");
		test.info("Select the users");
		test.info("Switch the button to orange member");
		test.info("Select the orange members");
		test.info("Click on save button");
		test.info("Click on default permission");
		test.info("EXPECTED RESULT:: It should not change the permission of users & orange users");
		Assert.assertEquals(a, "Orange Member");
		test.pass(a);
		Assert.assertEquals(a3, "Members");
		test.pass(a3);
		Assert.assertEquals(a1, "123");
		test.pass(a1);
		Assert.assertEquals(a4, "Akhil");
		test.pass(a4);
		Assert.assertEquals(a5, "Akshay");
		test.pass(a5);
		Assert.assertEquals(a6, "orange-switch-btn active");
		test.pass(a6);
		Assert.assertEquals(a7, "anvesh");
		test.pass(a7);
		Assert.assertEquals(a8, "asif");
		test.pass(a8);
		Assert.assertEquals(a2, "Default Permission Users can chat with 3 users , 2 orange users");
		test.pass(a2);
		Assert.assertEquals(a11, "5");
		test.pass(a11);
		Assert.assertEquals(a9, "SAVE");
		test.pass(a9);
		Assert.assertEquals(a10, "Permissions applied");
		test.pass(a10);
		Assert.assertEquals(a14, "DEFAULT PERMISSION");
		test.pass(a14);
		Assert.assertEquals(a12, "Default Permission Users can chat with 3 users , 2 orange users");
		test.pass(a12);
		Assert.assertEquals(a13, "5");
		test.pass(a13);
		test.log(Status.PASS,"ACTUAL RESULT::  It is not changing the permission of users & orange users");
		test.pass("Test Case:: TestCase PASSED");
		Thread.sleep(1000);
		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
