package grit_controls;

import org.junit.Assert;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class Trumpet {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("trumpet.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test00() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Click on trumpet");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should click on trumpet");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is clicking on trumpet");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println();
  		driver.close();
	}
	@Test
	public void test01() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(1000);
  		String a3=driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).getAttribute("value");
  		driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).click();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Click on enable");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Click on save button");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should select the enable radio button");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Save");
  		test.pass(a3);
  		String a5=driver.findElement(By.xpath("//div[@id='feedbackSection']")).getText();
  		Assert.assertEquals(a5, "Updated!");
  		test.pass(a5);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is selecting the enable radio button");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(1);
  		driver.close();
	}
	@Test
	public void test02() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(1000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("test");
  		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/span")).getText();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Search with valid user name in members");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Click on search");
  		test.info("Enter valid username");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should search the valid username");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Members");
  		test.pass(a3);
  		String a4=driver.findElement(By.xpath("//div[@data-search='test']")).getAttribute("data-search");
		Assert.assertEquals(a4,"test");
		System.out.println(a4);
		test.pass(a4);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is searching the valid username");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(2);
  		driver.close();
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(1000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("qweqwe");
  		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/span")).getText();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Search with invalid user name in members");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Click on search");
  		test.info("Enter invalid username");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should search the invalid username");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Members");
  		test.pass(a3);
  		String a4=driver.findElement(By.xpath("//div[@class='no-results-found']")).getAttribute("class");
		Assert.assertEquals(a4,"no-results-found");
		System.out.println(a4);
		test.pass(a4);
  		test.log(Status.PASS, "ACTUAL RESULT ::  No results found!");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(3);
  		driver.close();
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(1000);
  		String a7=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[1]/span[2]")).getText();
  		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/span")).getText();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Count the users in members");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Count the members");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should display count of the users");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Members");
  		test.pass(a3);
		Assert.assertEquals(a7,"88");
		System.out.println(a7);
		test.pass(a7);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is displaying count of the users");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(4);
  		driver.close();
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(1000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).click();
  		String a5=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).getAttribute("class");
  		Thread.sleep(1000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("test");
  		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/span")).getText();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Search with valid orange user in members");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Switch to orange user");
  		test.info("Click on search");
  		test.info("Enter valid username");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should search the valid username");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Members");
  		test.pass(a3);
  		Assert.assertEquals(a5, "orange-switch-btn active");
  		test.pass(a5);
  		String a4=driver.findElement(By.xpath("//div[@data-search='test']")).getAttribute("data-search");
		Assert.assertEquals(a4,"test");
		System.out.println(a4);
		test.pass(a4);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is searching the valid username");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(5);
  		driver.close();
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(1000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).click();
  		String a5=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).getAttribute("class");
  		Thread.sleep(1000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[1]/input")).sendKeys("qweqwe");
  		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/span")).getText();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Search with invalid orange user in members");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Switch to orange user");
  		test.info("Click on search");
  		test.info("Enter invalid username");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should search the invalid username");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Members");
  		test.pass(a3);
  		Assert.assertEquals(a5, "orange-switch-btn active");
  		test.pass(a5);
  		String a4=driver.findElement(By.xpath("//div[@class='no-results-found']")).getAttribute("class");
		Assert.assertEquals(a4,"no-results-found");
		System.out.println(a4);
		test.pass(a4);
  		test.log(Status.PASS, "ACTUAL RESULT ::  No results found!");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(6);
  		driver.close();
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(1000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).click();
  		String a5=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[1]/div[2]")).getAttribute("class");
  		Thread.sleep(1000);
  		String a7=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[1]/span[2]")).getText();
  		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/span")).getText();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Count the orange users in members");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Switch to orange users");
  		test.info("Count the members");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should display count of the orange users");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Members");
  		test.pass(a3);
  		Assert.assertEquals(a5, "orange-switch-btn active");
  		test.pass(a5);
		Assert.assertEquals(a7, "10");
		System.out.println(a7);
		test.pass(a7);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is displaying count of the orange users");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(7);
  		driver.close();
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(1000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[1]/input")).sendKeys("sai");
  		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/span")).getText();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Search with valid user name in Users who can initiate Trumpet");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Click on search in Users who can initiate Trumpet");
  		test.info("Enter valid username");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should search the valid username ");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Users who can initiate Trumpet");
  		test.pass(a3);
  		String a4=driver.findElement(By.xpath("//div[@data-search='sai']")).getAttribute("data-search");
		Assert.assertEquals(a4,"sai");
		System.out.println(a4);
		test.pass(a4);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is searching the valid username");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(8);
  		driver.close();
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(1000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[1]/input")).sendKeys("asdasd");
  		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/span")).getText();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Search with invalid user name");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Click on search");
  		test.info("Enter invalid username");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should search the invalid username");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Users who can initiate Trumpet");
  		test.pass(a3);
  		String a4=driver.findElement(By.xpath("//div[@class='no-results-found']")).getAttribute("class");
		Assert.assertEquals(a4,"no-results-found");
		System.out.println(a4);
		test.pass(a4);
  		test.log(Status.PASS, "ACTUAL RESULT ::  No results found!");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(9);
  		driver.close();
	}
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(1000);
  		String a7=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[1]/span[3]")).getText();
  		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/span")).getText();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Count the users in Users who can initiate Trumpet");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Count the users");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should display the count of the users");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Users who can initiate Trumpet");
  		test.pass(a3);
		Assert.assertEquals(a7,"5");
		System.out.println(a7);
		test.pass(a7);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is displaying count of the users");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(10);
  		driver.close();
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(1000);
  		String a7=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[1]/span[3]")).getText();
  		String a3=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/span")).getText();
  		Thread.sleep(1000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[2]/div[3]/span[2]")).click();
  		String a4=driver.findElement(By.xpath("//div[@data-search='Akhil']")).getAttribute("data-search");
  		//driver.findElement(By.xpath("//div[@data-userid='Department Admin']")).click();
  		Thread.sleep(1000);
  		String a5=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/span")).getText();
  		String a6=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[1]/span[3]")).getText();
  		String a8=driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).getAttribute("value");
  		driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).click();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Add the users & Click on save button");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Select the members");
  		test.info("Click on save button");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should add the users in who can initiate Trumpet");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a7, "5");
  		test.pass(a7);
  		Assert.assertEquals(a3, "Members");
  		test.pass(a3);
  		Assert.assertEquals(a8, "Akhil");
		test.pass(a8);
  		Assert.assertEquals(a4, "Save");
  		test.pass(a4);
  		Assert.assertEquals(a5, "Users who can initiate Trumpet");
  		test.pass(a5);
  		Assert.assertEquals(a6, "6");
  		test.pass(a6);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is adding the users in who can initiate Trumpet");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(11);
  		driver.close();
	}
	@Test
	public void test12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(1000);
  		String a7=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[1]/span[3]")).getText();
  		Thread.sleep(1000);
  		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[1]/div[2]/div[2]/div[3]/span[2]")).click();
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[2]/div[2]/span[3]")).click();
  		Thread.sleep(1000);
  		String a5=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/span")).getText();
  		String a6=driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[3]/div/div[2]/div/div[1]/span[3]")).getText();
  		String a4=driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).getAttribute("value");
  		driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).click();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Remove the users & Click on save button");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Remove the user in who can initiate trumpet");
  		test.info("Click on save button");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should remove the users in who can initiate Trumpet");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a5, "Users who can initiate Trumpet");
  		test.pass(a5);
  		Assert.assertEquals(a7, "6");
  		test.pass(a7);
  		Assert.assertEquals(a4, "Save");
  		test.pass(a4);
  		Assert.assertEquals(a6, "5");
  		test.pass(a6);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is removing the users in who can initiate Trumpet");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(12);
  		driver.close();
	}
	@Test
	public void test13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(2000);
  		WebElement e=driver.findElement(By.xpath("//div[@id='trumpetCannedMessageInput']"));
  		Actions ac=new Actions(driver);
  		ac.click(e).sendKeys("test").perform();
  		//driver.findElement(By.xpath("//*[@id=\"trumpetCannedMessageInput\"]")).sendKeys("test");
  		Thread.sleep(1000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[5]/div/div/div/div/div[1]/div[1]/div[2]/div")).click();
  		Thread.sleep(1000);
  		String a3=driver.findElement(By.xpath("//div[@id='trumpetAddedCannedMessagesWrapper']")).getText();
  		String a4=driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).getAttribute("value");
  		driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).click();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Add the canned messages & Click on save button");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Add canned messages");
  		test.info("Click on save button");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should add the canned msg");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Noted\n"
  				+ "Ok\n"
  				+ "Sure\n"
  				+ "Roger that\n"
  				+ "Thank you\n"
  				+ "👍\n"
  				+ "test");
  		test.pass(a3);
  		Assert.assertEquals(a4, "Save");
  		test.pass(a4);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is adding the canned msg");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(13);
  		driver.close();
	}
	@Test
	public void test14() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(2000);
  		WebElement e=driver.findElement(By.xpath("//div[@id='trumpetCannedMessageEmojiPreviewBtn']"));
  		Actions ac=new Actions(driver);
  		ac.click(e).perform();
  		driver.findElement(By.xpath(" /html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[5]/div/div/div/div/div[1]/div[2]/div/div[2]/div/span[6]")).click();
  		Thread.sleep(1000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[5]/div/div/div/div/div[1]/div[1]/div[2]/div")).click();
  		Thread.sleep(1000);
  		String a3=driver.findElement(By.xpath("//div[@id='trumpetAddedCannedMessagesWrapper']")).getText();
  		String a4=driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).getAttribute("value");
  		driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).click();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Add emoji canned messages & Click on save button");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Add emoji canned messages");
  		test.info("Click on save button");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should add emoji the canned msg");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Noted\n"
  				+ "Ok\n"
  				+ "Sure\n"
  				+ "Roger that\n"
  				+ "Thank you\n"
  				+ "👍\n"
  				+ "test\n"
  				+ "😉");
  		test.pass(a3);
  		Assert.assertEquals(a4, "Save");
  		test.pass(a4);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is adding emoji the canned msg");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(14);
  		driver.close();
	}
	@Test
	public void test15() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[5]/div/div/div/div/div[2]/div/div[8]/div/div[3]")).click();
  		Thread.sleep(1000);
  		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[5]/div/div/div/div/div[1]/div[1]/div[2]/div")).click();
  		Thread.sleep(1000);
  		String a3=driver.findElement(By.xpath("//div[@id='trumpetAddedCannedMessagesWrapper']")).getText();
  		String a4=driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).getAttribute("value");
  		driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).click();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Add the canned messages & Click on save button");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Remove emoji canned messages");
  		test.info("Click on save button");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should remove emoji the canned msg");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Noted\n"
  				+ "Ok\n"
  				+ "Sure\n"
  				+ "Roger that\n"
  				+ "Thank you\n"
  				+ "👍\n"
  				+ "test");
  		test.pass(a3);
  		Assert.assertEquals(a4, "Save");
  		test.pass(a4);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is removing emoji the canned msg");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(15);
  		driver.close();
	}
	@Test
	public void test16() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[5]/div/div/div/div/div[2]/div/div[7]/div/div[3]")).click();
  		Thread.sleep(1000);
  		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[5]/div/div/div/div/div[1]/div[1]/div[2]/div")).click();
  		Thread.sleep(1000);
  		String a3=driver.findElement(By.xpath("//div[@id='trumpetAddedCannedMessagesWrapper']")).getText();
  		String a4=driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).getAttribute("value");
  		driver.findElement(By.xpath("//input[@class='btn btn-default submit-btn']")).click();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Add the canned messages & Click on save button");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Remove canned messages");
  		test.info("Click on save button");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should remove the canned msg");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Noted\n"
  				+ "Ok\n"
  				+ "Sure\n"
  				+ "Roger that\n"
  				+ "Thank you\n"
  				+ "👍");
  		test.pass(a3);
  		Assert.assertEquals(a4, "Save");
  		test.pass(a4);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is removing the canned msg");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(16);
  		driver.close();
	}
	@Test
	public void test17() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//select[@id='trumpetMusicInputWrapper']")).click();
  		Thread.sleep(1000);
  		//driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[24]/div[2]/div[5]/div/div/div/div/div[1]/div[1]/div[2]/div")).click();
  		Thread.sleep(1000);
  		String a3=driver.findElement(By.xpath("//select[@id='trumpetMusicInputWrapper']")).getText();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Click on BUZZ music");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Click on BUZZ music");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should click on buzz music");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "Music Tone"
  				+ "Tone 1\n"
  				+ "Tone 2\n"
  				+ "Tone 3\n"
  				+ "Tone 4");
  		test.pass(a3);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is clicking on buzz music");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(17);
  		driver.close();
	}
	//@Test
	public void test18() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver = new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("sharath1");
  		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("123456");
  		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//div[@data-type='5']")).click();
  		Thread.sleep(2000);
  		driver.switchTo().frame(0);
  		driver.findElement(By.xpath("//div[@data-tab='4']")).click();
  		String a=driver.findElement(By.xpath("//div[@data-tab='4']")).getText();
  		Thread.sleep(1000);
  		String a1=driver.findElement(By.xpath("//div[@data-value='Trumpet']")).getText();
  		driver.findElement(By.xpath("//div[@data-value='Trumpet']")).click();
  		Thread.sleep(1000);
  		String a2=driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).getText();
  		driver.findElement(By.xpath("//label[@for='permissionTrumpetRadioEnable']")).click();
  		Thread.sleep(2000);
  		driver.findElement(By.xpath("//select[@id='trumpetMusicInputWrapper']")).click();
  		Thread.sleep(1000);
  		WebElement e=driver.findElement(By.xpath("(//option[@value='2'])[2]"));
  		e.click();
  		e.sendKeys(Keys.ENTER);
  		Thread.sleep(1000);
  		String a3=driver.findElement(By.xpath("(//option[@value='2'])[2]")).getText();
  		Thread.sleep(1000);
  		ExtentTest test=extent.createTest("Click on BUZZ music");
  		test.log(Status.INFO, "Chrome Browser Launched Successfully");
		test.info("Navigate to URL : http://192.168.2.55:8083");
		test.info("Enter username : sharath1");
		test.info("Enter password : 123456");
		test.info("Click on login button");
		test.info("Click on dashboard");
  		test.info("Click on controls");
  		test.info("Click on trumpet");
  		test.info("Select enable");
  		test.info("Click on BUZZ music");
  		test.log(Status.INFO, "EXPECTED RESULT ::  It should click on buzz music");
  		Assert.assertEquals(a, "Controls");
  		test.pass(a);
  		Assert.assertEquals(a1, "Trumpet");
  		test.pass(a1);
  		Assert.assertEquals(a2, "Enable");
  		test.pass(a2);
  		Assert.assertEquals(a3, "");
  		test.pass(a3);
  		test.log(Status.PASS, "ACTUAL RESULT ::  It is clicking on buzz music");
  		test.log(Status.PASS, "Test Case:: TestCase PASSED");
  		System.out.println(18);
  		driver.close();
	}
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
