package grit_controls;

import java.awt.AWTException;
import java.io.IOException;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class VoiceMsg {
	WebDriver driver;
	ExtentHtmlReporter htmlReporter;
	ExtentReports extent;

	String extentReportImage = System.getProperty("user.dir")+ "extentReportImage.png";
	@BeforeSuite
	public void StartTest() {
		htmlReporter = new ExtentHtmlReporter("voicemsg.html");
		extent = new ExtentReports();
		extent.attachReporter(htmlReporter);
	}
	@Test
	public void test() throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioDisable\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='input-microphone-btn input-action-btn']")).click();
		Thread.sleep(500);
		String a2=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		Thread.sleep(1000);
		ExtentTest test=extent.createTest("By clicking on Disable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Disable button");
		test.info("click on save button");
		test.info("Click on any user");
		test.info("click on any voice message in the user page");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should not forward, Download & send the voice message");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a2, "Voice message is disabled");
		test.pass(a2);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding, downloading & sending the voice message");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test01() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='input-microphone-btn input-action-btn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//span[@id='sendMessageBtn']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting Enable radiobutton & Don't click on any checkboxes");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on any user");
		test.info("Click on voice msg & Record the voice");
		test.info("Click on send");
		test.info("click on any voice message in the user page");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should not forward and Download the voice message & It should send the voice msg");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding & downloading the voice message & It is sending the voice msg");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test02() throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionUser']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionOrangeMember']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_9-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting all the checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("click on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on any user");
		test.info("click on any voice message in the user page");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the voice message");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test03() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionUser']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionOrangeMember']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By de-selecting all the checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("de-select on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on any user");
		test.info("click on any voice message in the user page");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should not forward and Download the voice message");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding & downloading the voice message");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test04() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionUser']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath web plain");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_9-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting user checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("select on user checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Login with normal user");
		test.info("Click on user");
		test.info("Select any voice message");
		test.info("click on any voice message in the user page");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message in user account");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the voice message in only user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test05() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionUser']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath web plain");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By Deselecting the user checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("click on user checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login normal user");
		test.info("Click on user");
		test.info("Select the voice message");
		test.info("Right click on voice message & forward to the user");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should not forward and Download the voice message for User");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding & downloading the voice message for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test06() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath web plain");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='attachment-forward-option']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By Deselecting the user checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("Deselect the user checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login normal user");
		test.info("Click on user");
		test.info("Select the voice message");
		test.info("Click on forward icon");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should not forward and Download the voice message for User");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding & downloading the voice message for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test07() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionUser']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("sharath web plain");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='attachment-forward-option']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_9-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting the user checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("click on user checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login normal user");
		test.info("Click on user");
		test.info("Select the voice message");
		test.info("Click on forward icon");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message for User");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the voice message for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test08() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionOrangeMember']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("orange10");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_9-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='Doo']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting orange member checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("select on user checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Login with orange user");
		test.info("Click on user");
		test.info("Select any voice message");
		test.info("click on any voice message in the user page");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message in user account");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the voice message in only user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test09() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionOrangeMember']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("orange10");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By Deselecting the orange member checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("click on orange member checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login orange user");
		test.info("Click on user");
		test.info("Select the voice message");
		test.info("Right click on voice message & forward to the user");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should not forward and Download the voice message for User");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding & downloading the voice message for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test10() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("orange10");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='attachment-forward-option']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By Deselecting the orange member checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("Deselect the orange member checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login orange user");
		test.info("Click on user");
		test.info("Select the voice message");
		test.info("Click on forward icon");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should not forward and Download the voice message for User");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding & downloading the voice message for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test11() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionOrangeMember']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("orange10");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='android']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='attachment-forward-option']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_9-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='Doo']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting the orange member checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("click on orange member checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login orange user");
		test.info("Click on user");
		test.info("Select the voice message");
		test.info("Click on forward icon");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message for User");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the voice message for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test12() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='ios e2ee']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_208-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='ios e2ee']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting TM-Admin checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("Select on checkboxes of TM-admin");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Login with TM-Admin user");
		test.info("Click on user");
		test.info("Select any voice message");
		test.info("Right click on voice message & Click on forward");
		test.info("Send to the user");
		test.info("Click on Download for voice message");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message in TM-admin users only");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is downloading & forwarding the voice message for only TM-admin user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test13() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='ios e2ee']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By deselecting the TM-Admin checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("click on Tm-admin checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on logout");
		test.info("Login with Tm-admin user");
		test.info("Click on user");
		test.info("Select any voice message");
		test.info("Right click on voice message & Click on forward");
		test.info("Send to the user");
		test.info("Click on Download for voice message");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message in Tm-admin users only");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is downloading & forwarding the voice message for only TM-admin user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test14() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='ios e2ee']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='attachment-forward-option']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By Deselecting the TM-admin checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("Deslect the Tm-admin checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login TM-admin user");
		test.info("Click on user");
		test.info("Select the voice message");
		test.info("Click on forward icon");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should not forward and Download the voice message for User");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding & downloading the voice message for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test15() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='ios e2ee']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='attachment-forward-option']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_9-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='ios e2ee']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting the TM-admin checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("click on TM-admin checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login TM-admin user");
		test.info("Click on user");
		test.info("Select the voice message");
		test.info("Click on forward icon");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message for User");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the voice message for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test16() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionDepartmentAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("ios");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath web plain']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_244-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='sharath web plain']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting Department Admin checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : android");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("select on Department Admin checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Login the Department admin user");
		test.info("Click on user");
		test.info("Select any voice message");
		test.info("Right click on voice message & Click on forward");
		test.info("Send to the user");
		test.info("Click on Download for voice message");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message in Department admin users only");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is downloading & forwarding the voice message for only Department admin user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test17() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionDepartmentAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(2000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("ios");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath web plain']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By deselecting Department Admin in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("click on Department Admin checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Login the Department admin user");
		test.info("Click on user");
		test.info("click on voice message in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message in Department Admin");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the voice message in Department admin");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test18() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("ios");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath web plain']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='attachment-forward-option']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By Deselecting the department admin checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("Deslect the department admin checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login department admin user");
		test.info("Click on user");
		test.info("Select the voice message");
		test.info("Click on forward icon");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should not forward and Download the voice message for User");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding & downloading the voice message for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test19() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionDepartmentAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("ios");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath web plain']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='attachment-forward-option']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_9-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='sharath web plain']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting the department admin checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("click on department admin checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login department admin user");
		test.info("Click on user");
		test.info("Select the voice message");
		test.info("Click on forward icon");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message for User");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the voice message for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test20() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionLocationAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("samsung");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath web plain']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.moveToElement(e).contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_244-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='sharath web plain']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting location Admin checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("select on Location Admin checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Login the location admin user");
		test.info("Click on user");
		test.info("Select any voice message");
		test.info("Right click on voice message & Click on forward");
		test.info("Send to the user");
		test.info("Click on Download for voice message");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message in Location admin users only");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is downloading & forwarding the voice message for only Location admin user");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test21() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionLocationAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("samsung");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath web plain']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(3000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By deselecting location Admin in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("click on location Admin checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Login the location admin user");
		test.info("Click on user");
		test.info("click on voice message in the userpage");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message in Location Admin");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the voice message in location admin");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test22() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("samsung");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath web plain']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='attachment-forward-option']")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(1000);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By Deselecting the location admin checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("Deslect the location admin checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login location admin user");
		test.info("Click on user");
		test.info("Select the voice message");
		test.info("Click on forward icon");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should not forward and Download the voice message for User");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding & downloading the voice message for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test23() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionLocationAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/div[1]/div[1]/div[1]/div[1]/div[5]/div/span[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("samsung");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='sharath web plain']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@class='attachment-forward-option']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_9-1']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='sharath web plain']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting the location admin checkbox in Enable radiobutton");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("click on location admin checkbox");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Logout the user");
		test.info("Click on login");
		test.info("Login location admin user");
		test.info("Click on user");
		test.info("Select the voice message");
		test.info("Click on forward icon");
		test.info("Click on Download");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message for User");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the voice message for User");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test24() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		/*
		 * driver.findElement(By.xpath("//label[@for='voiceMessagePermissionUser']")).
		 * click(); Thread.sleep(1000); driver.findElement(By.xpath(
		 * "//label[@for='voiceMessagePermissionOrangeMember']")).click();
		 * Thread.sleep(1000);
		 * driver.findElement(By.xpath("//label[@for='voiceMessagePermissionAdmin']")).
		 * click(); Thread.sleep(1000);
		 */
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(2000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='web created group(Std )']")).click();
		Thread.sleep(2000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='forwardUser_730-2']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"modalForwardSendMessageBtn\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-name='Add IOS user (std)']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By selecting all the checkbox in Enable radiobutton in Groups");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("select all the checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on any group");
		test.info("click on any voice message in the group page");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should forward and Download the voice message in any Group");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		String a1=driver.findElement(By.xpath("//span[@class='forward-conversation-label-icon']")).getAttribute("class");
		Assert.assertEquals(a1, "forward-conversation-label-icon");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is forwarding & downloading the voice message in any group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	@Test
	public void test25() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "/home/tvisha/Downloads/chromedriver_linux64/chromedriver");
		driver=new ChromeDriver();
		driver.get("http://192.168.2.55:8083");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("android");
		driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123456");
		driver.findElement(By.xpath("//button[@id='bG9naW5CdG4']")).click();
		Thread.sleep(1000);
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//div[@data-type='5']")).click();
		driver.switchTo().frame(0);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/div[4]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//div[@data-value='Voice Message']")).click();
		driver.findElement(By.xpath("//*[@id=\"permissionVoiceMessageRadioEnable\"]\n")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionUser']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionOrangeMember']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//label[@for='voiceMessagePermissionAdmin']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div[2]/div/div[26]/div[2]/div[4]/input")).click();
		Thread.sleep(1000);
		String actual=driver.findElement(By.xpath("//div[@class='feedback-section']")).getText();
		Thread.sleep(1000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@data-name='web created group(Std )']")).click();
		Thread.sleep(1000);
		WebElement e=driver.findElement(By.xpath("//div[@class='audio-attachment-wrapper']"));
		Actions ac=new Actions(driver);
		ac.contextClick(e).perform();
		Thread.sleep(1000);
		WebElement e1=driver.findElement(By.xpath("//a[@data-action='forward']"));
		ac.doubleClick(e1).perform();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id=\"forwardMessageSendBtn\"]")).click();
		Thread.sleep(1000);
		String a=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//span[@id='forwardMessageCloseBtn']")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//a[@class='download-attachment']")).click();
		Thread.sleep(500);
		String a1=driver.findElement(By.xpath("//div[@id='snackbar']")).getText();
		Thread.sleep(2000);
		ExtentTest test=extent.createTest("By de-selecting all the checkbox in Enable radiobutton in Groups");
		test.log(Status.INFO, "Chrome Browser launching Successfully");
		test.info("Navigate to Url");
		test.info("User name : ios");
		test.info("Password:123456");
		test.info("Login:click on login");
		test.info("Click on AdminDashboard");
		test.info("click on controls");
		test.info("Click on voice message");
		test.info("click on Enable button");
		test.info("de-select on checkboxes");
		test.info("click on save button");
		test.info("GoTo chat");
		test.info("Click on any Group");
		test.info("click on any voice message in the group page");
		test.info("Click on Download and Forward");
		test.info("EXPECTED RESULT ::  It should not forward and Download the voice message in Group page");
		Assert.assertEquals(actual, "Updated!");
		test.pass(actual);
		Assert.assertEquals(a, "Forwarding Voice Message is restricted");
		test.pass(a);
		Assert.assertEquals(a1, "Downloading Voice Message is restricted");
		test.pass(a1);
		test.log(Status.PASS ,"ACTUAL RESULT ::  It is not forwarding & downloading the voice message in Group");
		test.pass("Test Case:: TestCase PASSED");
		driver.close();
	}
	
	@AfterSuite
	public void endTest() {
		extent.flush();
	}
}
